### ISSUE TITLE
JSONModel crashes when expecting a number but getting a JSON 'null'.

### ISSUE THREAD

**Issue by j-h-a** [JSONModel/JSONModel#101]
For Obj-C Properties that are defined as scalar types, JSONModel expects an `NSNumber` to be initialised with the the number. However, when the JSON contains `null` then an `NSNull` is created and JSONModel tries to send (for example) `floatValue` to it which results in an unrecognised selector error.

I have a solution in mind:
1. Create another Protocol: `NotNull` which means the corresponding JSON value must not be `null`.
2. All scalar properties will be backed by a `NotNull` `NSNumber`. If you want a number that can also be `null` (rather than zero), use an `NSNumber` property explicitly and check if it's actually an `NSNull` object instead before using it.

Benefits:
a) allows the `NotNull` protocol to be used anywhere (not just on scalars) to tighten up validation;
b) protects against crashes caused by bad data;
c) gives better error reporting with a `JSONModelError`.

I will work on this over the coming week (it's not that big, but I have other things on too), If anyone has any feedback or thoughts, please let me know.

**Comment by kukuji** [comment]
Hi icanzlib, is there a way to replace "null" value with empty value (like "" for NSString or 0 for int), or do we have a way to avoid the initialization to fail when you have null value?

Thanks
