### ISSUE TITLE
Convert model to JSON with specific properties 

### ISSUE THREAD

**Issue by Janak-Nirmal** [JSONModel/JSONModel#125]
Hey, 

**Again its me This is not an issue**, I have model as 

```
@interface Question : JSONModel
@property (nonatomic,assign) NSInteger intQuestionId;
@property (nonatomic,strong) NSString *strQuestion;
@property (nonatomic,assign) NSInteger intSelectedOption;
@end

@implementation Question
//Marking property as optional
+(BOOL)propertyIsOptional:(NSString*)propertyName
{
    if([propertyName isEqualToString:@"intSelectedOption"])
        return YES;

    return NO;
}
@end
```

For converting question array to json dictionary array I use

`NSArray *arrDict = [Question arrayOfDictionariesFromModels:_arrQuestions];`

If I want only 2 property i.e. intQuestionId and intSelectedOption when converted back to JSON how can I do that ?

Thanks
Janak Nirmal

**Comment by xplatsolutions** [comment]
I can't seem to find this available, any insights? I want to export specific properties of an NSArray of JSONModel subclass objects.
