### ISSUE TITLE
Can't make optional BOOL  property

### ISSUE THREAD

**Issue by skywinder** [JSONModel/JSONModel#173]
I have a class like

@interface MyClass : JSONModel
@property (nonatomic) BOOL enabled;
@property (nonatomic, retain) NSString *name;
@end

So, I can't make enabled key optional (because of I can't assign protocols to non-NS Class).
The only way that I found:
 use
 `+(BOOL)propertyIsOptional:(NSString*)propertyName
    {
            return YES;
   }`

But it's not good solution.

**Comment by sudhiryadav** [comment]
I tried with this but still no luck :
`+(BOOL)propertyIsOptional:(NSString*)propertyName
{
    if ([propertyName isEqualToString: @"isInEurope"])
    {
        return YES;
    }
    return NO;
}`
