### ISSUE TITLE
Multidimensional array with unnamed entries

### ISSUE THREAD

**Issue by SuperMario77** [JSONModel/JSONModel#29]
Hello,

I tried a lot of things, but I can't get it work. Is it possible to parse something like this from JSON to a model class? If yes, please tell me how.

<pre>            {
                "id": 490757198516,
                "height": 4,
                "width": 4,
                "gameField":
                [
                    [
                        {
                            "id": 13,
                            "pictureId": 6
                        },
                        {
                            "id": 3,
                            "pictureId": 1
                        }
                    ],
                    [
                        {
                            "id": 1,
                            "pictureId": 0
                        },
                        {
                            "id": 8,
                            "pictureId": 4
                        }
                    ]
                ]
            }
</pre>

The gameField is a 2x2 array of GameField objects. In Java REST Service it is defined as "GameField gameField[2][2];" And GameField is a class with member variable "id" and "pictureId". 

Best regards,
Mario

**Comment by shashank16** [comment]
Hello,

I have pasted a sample JSON response. It consists 2 subArrays in an array. Is it possible to parse something like this from JSON to a model class? If yes, please tell me how.


"value": {
                            "attributeOptions": [
                                [
                                    {
                                        "imageUrl": "http://rukmini1.flixcart.com/image/{@width}/{@height}/mobile/4/u/g/apple-iphone-5s-original-imadpppc9k3gzdjz.jpeg?q={@quality}",
                                        "value": "Gold"
                                    },
                                    {
                                        "imageUrl": "http://rukmini1.flixcart.com/image/{@width}/{@height}/mobile/4/y/h/apple-iphone-5s-original-imadpppch2n6hhux.jpeg?q={@quality}",
                                        "value": "Silver"
                                    },
                                    {
                                        "imageUrl": "http://rukmini1.flixcart.com/image/{@width}/{@height}/mobile/z/h/f/apple-iphone-5s-original-imadpppc54zfpj9c.jpeg?q={@quality}",
                                        "value": "Space Grey"
                                    }
                                ],
                                [
                                    {
                                        "value": "16 GB"
                                    },
                                    {
                                        "value": "32 GB"
                                    },
                                    {
                                        "value": "64 GB"
                                    }
                                ]
                            ],

**Comment by shashank16** [comment]
"attributeOptions":[
[
{"imageUrl": "http://rukmini1.flixcart.com/image/{@width}/{@height}/mobile/4/u/g/apple-iphone-5s-original-imadpppc9k3gzdjz.jpeg?q={@quality}",…},
{"imageUrl": "http://rukmini1.flixcart.com/image/{@width}/{@height}/mobile/4/y/h/apple-iphone-5s-original-imadpppch2n6hhux.jpeg?q={@quality}",…},
{"imageUrl": "http://rukmini1.flixcart.com/image/{@width}/{@height}/mobile/z/h/f/apple-iphone-5s-original-imadpppc54zfpj9c.jpeg?q={@quality}",…}
],
[
{"value": "16 GB"},
{"value": "32 GB"},
{"value": "64 GB"}
]
],

**Comment by billinghamj** [comment]
As @icanzilb said, JSONModel does not support this case at present. That being said, you can always declare the property as a plain `NSArray`, then override the setter and handle this particular case yourself.

**Comment by reshy526** [comment]
06 Апр 2016 г. 13:10 пользователь "shashank16" <notifications@github.com>
написал:
