### ISSUE TITLE
Attribute Mapping

### ISSUE THREAD

**Issue by aaronrogers** [JSONModel/JSONModel#3]
I love how lightweight this is.  The only issue I have is that I want to map underscore attribute names from rails (ie hair_color) to a more iOS friendly camel case (ie hairColor).  Any plans for that?

**Comment by fresh83** [comment]
Why do i get errors if i send over a string with all caps and underscores?  such as  typeOfContent being a string that can return things like  DEFAULT_PHOTO?   and how do I fix it?
