### ISSUE TITLE
Bug: UInt32 causes JSONModel to throw exception on some devices

### ISSUE THREAD

**Issue by timothyrudd** [jsonmodel/jsonmodel#315]
I am using a UInt32 property in my JSONModel class to handle integer data that needs to be 32 bits in length. I am also using propertyIsIgnored: to ignore this property.

These are the devices I am using JSONModel 1.0.2 on these devices

- iPad 3rd Generation (32 bit) iOS 8.3
- iPhone 5s (64 bit) iOS 8.3

This will work on my iPhone but when I run it on the iPad I get the following error output:

> *** Terminating app due to uncaught exception 'JSONModelProperty type not allowed', reason: 'Property type of \<class\>.\<UInt32 property\> is not supported by JSONModel.'

I did some debugging and I tracked it down to __inspectProperties in JSONModel.m right before the exception is thrown. The iPad's UInt32 propertyType is `L` which is not in valueTransformer.primitivesNames, whereas the iPhone's UInt32 propertyType is `I` which is and is an NSInteger.

Adding `@"L": @"long"` to _primitaveNames in JSONValueTransformer.m seems to solve the issue.

```objc
_primitivesNames = @{@"f":@"float", @"i":@"int", @"d":@"double", @"l":@"long", @"c":@"BOOL", @"s":@"short", @"q":@"long",
                             //and some famos aliases of primitive types
                             // BOOL is now "B" on iOS __LP64 builds
                             @"I":@"NSInteger", @"Q":@"NSUInteger", @"B":@"BOOL",
                             
                             // 32 bit int in 32 bit iOS
                             @"L": @"long",
                             
                             @"@?":@"Block"};
```

**Comment by billinghamj** [comment]
Having thought about this quite a few times over the last year or so, I have come to the conclusion that JSONModel doesn't (and shouldn't) support particularly specific property types. It is intended to deserialize into an instance of a class which directly corresponds with the JSON data.

As such, only `NSInteger` & `NSUInteger` are supported at present.
