### ISSUE TITLE
NSSet transformation won't work

### ISSUE THREAD

**Issue by jzarzuela** [jsonmodel/jsonmodel#324]
I have a property that is declared as NSSet<ModelEntity>.

When I try to get to JSON string representation I get an error because my entity can't be managed. 

I have seen in the code that the NSSet is transformed into an NSArray, but leaving all the instances unconverted. If I declare the property as NSArray<ModelEntity> everything works well because the elements are transformed into NSDictionary.

Even if the default transformer for NSSet worked properly (creating dictionaries as the other does) it wouldn't be able to do the reverse transformation because it will receive just the NSDictionary items without any context (what should I transform these dictionaries into?).

Transformers should receive "protocol" information, at least for collections, In  order to work.

So the only solution I've found is to create a custom getter/setter and do the transformation myself. 

This should be possible automatically between collections.

**Comment by billinghamj** [comment]
Yeah, I think we should probably support all collection types in a more generic way.

**Comment by billinghamj** [comment]
JSONModel is intended to (de)serialize to/from instances of classes which directly correspond to the JSON data. As such, I'm not currently intending on supporting collection types other than NSArray and NSDictionary.
