### ISSUE TITLE
NSNull saved in optional property is not exported to NSDictionary

### ISSUE THREAD

**Issue by fins** [jsonmodel/jsonmodel#348]
I have some properties that needs to be optional. It looks like it is not possible to export this model with optional properties using toDictionary method in such way that NSNull will be saved in the NSDictionary. The correct behavior would be to skip only nil values from JSONModel when exporting to NSDictionary but [NSNull null] from JSONModel should be exported to NSDictionary. This way I could send json with null's to web service even for optional properties which currently seems to be impossible even when I explicitly set them to NSNull instead of nil.

**Comment by billinghamj** [comment]
Optional properties containing null values are ignored when serializing.

**Comment by fins** [comment]
It would be good to have an option to force converting NSNull to null in json for optional properties as currently if we use optional properties then afaik there is no way to convert a model to json with null in it (and sometimes it would be useful when we need to send a null to a web service).

**Comment by billinghamj** [comment]
I have many cases where I need to send `null` to a web service. `NSNull` does seem like a good way of explicitly stating that you do want `null` to be sent.

I'd propose changing the default behavior to serialize instances of `NSNull` as `null` in all cases - even for properties marked as optional. Any opinions @icanzilb / @dbachrach ?

**Comment by dbachrach** [comment]
Yes I agree that this should definitely be possible. This will be a breaking change, though. Instead should we have this be opt in via a method:

```objc
- (BOOL)shouldSerializeNulls
{
    return NO; // Default
}
```

**Comment by billinghamj** [comment]
How often is `NSNull` actually used though? Surely in every normal use case, you'd just set it to `nil`. Along with that, sending `null` to most APIs is the same as not providing a value.

I'm just a tad concerned about the number of `shouldXyz` methods we're ending up with when really the default should be changed.

**Comment by icanzilb** [comment]
I think we should change the default behavior. 

In case a null comes in from the server for an optional value - then JSONModel automatically converts that to nil so your "incoming" model would have nil for that property (or it will not be set in other words). So - if you are exporting your model to JSON to send it over to the server and you DO have an NSNull object stored in that property - it looks like you explicitly did set this value yourself - I can't see any other reason why you would have this value stored in an optional property.

**Comment by billinghamj** [comment]
Yes, that's my thought process also.

**Comment by dbachrach** [comment]
This seems fair. Let's make sure to call it out in the release notes.
