### ISSUE TITLE
double as primitive type can not get the full name 

### ISSUE THREAD

**Issue by yigit26** [jsonmodel/jsonmodel#351]
Hi,
In JsonModel.m on line 659 
propertyType = valueTransformer.primitivesNames[propertyType]; returns nil.

Because propertyType is ^d so above line can not get the full name of the primitive type.

Printing description of propertyAttributes:
T^d,N,V_TGunlukDoz

Do we have to add @"^d" to valueTransformer.primitivesNames 
There is @"d":@"double" but it's not enough.

Best regards

**Comment by Johnykutty** [comment]
Can you paste the input JSON string?

I am also learning JSONMmdel in deep. If you can provide the input string, I can also understand and check the issue.

Regards, 
Johny
