### ISSUE TITLE
Creating category for JSONValueTransformer leads to compiler warning.

### ISSUE THREAD

**Issue by Igotit** [JSONModel/JSONModel#42]
I follow the instruction that creating category to override NSDateFromNSString method to handle different date time format.

Then the compiler warns "Category is implementing a method which will also be implemented by its primary class". 

I did some research and find a way to suppress the warning by add: #pragma clang diagnostic ignored "-Wobjc-protocol-method-implementation". But the linker is still warning...

Anyway, I think overriding those method by  a subclass of JSONValueTransformer would be much better. Why not add a property to the JSONModel class that receive customized value transformer.

**Comment by vaddieg** [comment]
I suggest to extend existing JSONValueTransformer in this way to cover more typical usecases 
```objc
#pragma mark - number <-> date
- (NSDate*)NSDateFromNSNumber:(NSNumber*)number
{
    if (strncmp(number.objCType, @encode(long long), sizeof(long long)) == 0) {
        // milliseconds (native for java backends date representation)
        return [NSDate dateWithTimeIntervalSince1970:[number longLongValue] / 1000.0];
    } else {
        return [NSDate dateWithTimeIntervalSince1970:number.doubleValue];
    }
    
}

```
