### ISSUE TITLE
JSONModel organization

### ISSUE THREAD

**Issue by icanzilb** [JSONModel/JSONModel#493]
@billinghamj I was thinking that it isn't all too fair if JSONModel is still maintained from my personal account on GitHub. I'm still keeping an eye on the repo issues but I have less and less time to answer any.

I think I'll create a new org on GitHub and call it JSONModel - then give you and myself admin rights (or whatever it's called) so that other people could also feel like contributing - so they don't feel like they are contributing to my own repo. 

Any thoughts?

**Comment by billinghamj** [comment]
Yeah, I think that'd be great 😄  :shipit:

**Comment by billinghamj** [comment]
Very much welcome others' thoughts also

**Comment by icanzilb** [comment]
@billinghamj I'm about to transfer the repo to https://github.com/JSONModel , any last objections? Anyone else?

**Comment by billinghamj** [comment]
Nope, it should be pretty seamless. GitHub does automatically redirect everything. We should just make sure to update CocoaPods to the new URLs for the next release.

**Comment by icanzilb** [comment]
this has also been my experience in the past, so I'm gonna go ahead and just do it :)

**Comment by icanzilb** [comment]
ok, done

**Comment by icanzilb** [comment]
I also updated the podspec https://github.com/JSONModel/JSONModel/blob/master/JSONModel.podspec, the next version we will cut from the new location

**Comment by billinghamj** [comment]
Great.
