### ISSUE TITLE
Deprecate bad practice & globally polluting code

### ISSUE THREAD

**Issue by billinghamj** [JSONModel/JSONModel#497]
JSONModel includes a number of features which can lead to confusion or unexpected behaviour, and issues being opened. I think it would be worth marking these as deprecated, then removing them entirely if we hit v2 at any point.

Specifically, I personally think the following things should be deprecated:

- [ ] **all networking code (everything in the "JSONModelNetworking" folder)**

  People regularly want greater control over how the networking classes operate, but we always decline and close the issue because it is intended to be simple. Given how high quality the built-in Foundation networking and many external request libraries are, I think the amount of value provided by the JSONModel networking is probably less than the hassle created by its limitations.

- [ ] **the global key mapper (`+ setGlobalKeyMapper:`)**

  Setting the global key mapper makes some key mapper functionality impossible (i.e. deciding not to modify the name of a key) as seen in #496, and it pollutes the global scope, which could be an issue if a library used it.

- [ ] **the `Index` property protocol**

  This protocol allows JSONModel to identify two different objects as equal based on an identifying property. This differs from the behavior of `isEqual:` as defined in Foundation. It does seem better to defer this decision making to the application anyway though.

Given v1 has been out for a little while, mostly everything is reasonably settled and stable, etc. - it seems like a good opportunity to look towards which major changes might want to be made for a possible future v2.

These features would be marked as deprecated (i.e. a warning), but would still function exactly as-is, so no breaking changes would occur.

I so also think that the way the `JSONValueTransformer` class works could be improved to allow it to be used in an isolated non-singleton way, but that would be a more drastic change which I think probably is best kept out of scope for now.

These are only my initial thoughts on the matter. Any actual actions taken would only happen if the other maintainers agree, so I'm keen for your opinions.

**Comment by icanzilb** [comment]
I would agree in a ♥️beat to remove the networking from `JSONModel` that was a stupid idea to start with but at the time I had to insight into how difficult networking was :) I think it currently only confuses people into believing they can do their app's networking with it but in the end they end up wishing for more, which isn't there. 👍

**Comment by billinghamj** [comment]
Okay great. That one is pretty clear cut, so I'll go ahead and flag it as deprecated, but leave all the actual functionality in place.

The others probably need a bit more thought.

**Comment by icanzilb** [comment]
re `Index` - I'm not sure many people even know about this. I certainly must admit have almost never used it. But hey - you'd be surprised in what ways people use JSONModel that I have never thought about. To be fair I'd get rid of `Index` too - I'll certainly not miss it.

About the global key mapper ... I see this as a useful feature, I've worked on apps that used many different models and of course all of them used camel case and of course all the PHP backend used underscore case so something like the global key mapper solves this in one line of code for ever ...

**Comment by billinghamj** [comment]
Index could be useful for some things, but the main issue is it kinda falsely declares equality. It returns `YES` even if all of the other properties are different, if just the ID field is equal. It seems to me a bit misleading and better left to the application using it.

The global key mapper is generally useful, but the same thing can be achieved by having a base model class in the application code. Personally, I think the base model approach is much better because it doesn't affect anything else using JSONModel, and it doesn't suffer from the problem mentioned in #496.

**Comment by solarplexus6** [comment]
In the context of #496 I would also favor the base model aproach - you can achieve the same thing, at the same time being more explicit. And because of the one weird line mentioned in #496 you can't really override global keymapper now.

**Comment by icanzilb** [comment]
Yeah this initially covered the cases in which people would fetch objects as JSON from the web and will merge to their database locally. So `Index` is a way to indicate which of your properties is your unique ID; however ... you are absolutely right that the default `isEqual:` implementation is completely wrong. Which I think only proves nobody has used this feature ever :)

**Comment by billinghamj** [comment]
Okay, so I'd say with regards to `Index`, we should deprecate the protocol due to it causing likely unexpected behavior on the `isEqual:` method. (Since we really can't "correct" `isEqual:` as it would be a breaking change)

In the future if there is demand, we could add something which has the same effect, but with a comparison method whose behavior is more explicit and clear.

**Comment by billinghamj** [comment]
Okay, I have made individual PRs for each of the deprecations I suggested. Might as well move discussion to those instead, so I'll close this one.

Networking - #498 
Index protocol - #499 
Global key mapper - #500
