### ISSUE TITLE
Array of sub-objects does not map

### ISSUE THREAD

**Issue by danipralea** [jsonmodel/jsonmodel#502]
Hello 

I have this
```

@interface FeedModel : ChatProductModel

@property (nonatomic, assign) BOOL inWishlist;
@property (nonatomic, strong) NSArray <StylistModel *> *stylist;

@end
```

- `ChatProductModel` is also a `JSONModel` descendant, and so is `StylistModel`

When I try to map a `FeedModel`, the `stylist` array is an array of dictionaries, and not `StylistModel` objects.
Any idea? Or my only option is to make a custom mapping?

**Comment by billinghamj** [comment]
JSONModel does not (cannot) support Obj-C generics. You can do either one of the following (not both):

```objc
@protocol StylistModel;

@interface FeedModel : ChatProductModel

@property (nonatomic, assign) BOOL inWishlist;
@property (nonatomic, strong) NSArray <StylistModel *> <StylistModel> *stylist;

@end
```

```objc
@implementation FeedModel

+ (Class)classForCollectionProperty:(NSString *)propertyName
{
  if ([propertyName isEqualToString:@"stylist"])
    return [StylistModel class];

  return nil;
}

@end
```

**Comment by danipralea** [comment]
Thank you very much @billinghamj !
Have the most awesome end of a week! 😄

**Comment by billinghamj** [comment]
No worries - thanks! :)
