### ISSUE TITLE
Analysis of JSONModel produces warnings

### ISSUE THREAD

**Issue by kerrmarin** [jsonmodel/jsonmodel#503]
Hey,

Running the static analysis tool on JSONModel produces the following warning:

`Method accepting NSError** should have a non-void return value to indicate whether or not an error occurred`

It seems to be from JSONModel.m:1301 -
`- (void)mergeFromDictionary:(NSDictionary *)dict useKeyMapping:(BOOL)useKeyMapping error:(NSError **)error`

I'm using Xcode 7.3.1

Would be great to fix this, happy to make a PR if necessary.

**Comment by billinghamj** [comment]
Hmm I'd personally say that warning seems a little pedantic and more related to having an API design which matches usual Obj-C standards than being a real issue. However, I suppose it's probably worth doing anyway.

I'm fairly certain that adding a return type would not be a breaking change for any existing code, so we should be able to add this immediately without any consequence. We should also add a test case for it though.

If you'd be happy to provide a PR with a unit test or two checking the behavior, that'd be great :)

**Comment by billinghamj** [comment]
Merged as dda1a2d72630c9815917178bb0d1577f5beed169
