### ISSUE TITLE
Release Permission/Access

### ISSUE THREAD

**Issue by billinghamj** [jsonmodel/jsonmodel#506]
@icanzilb What do you think about possibly giving me access to push to CocoaPods Trunk? This would allow me to do smaller patch releases more regularly rather than batching together lots of changes into a big release.

**Comment by billinghamj** [comment]
@icanzilb Could you respond to this please? We do need to find a way to allow for regular & expedient releases.

**Comment by icanzilb** [comment]
yup, lost track of this one sorry, let me have a look right now

**Comment by icanzilb** [comment]
@billinghamj can you send me your cocoapods email to add you? Send it via a DM on Twitter or email

**Comment by billinghamj** [comment]
Ah, it's already public - can be here :) james [at] billingham [dot] net

**Comment by icanzilb** [comment]
that's different than what you have on your github account... 

anyway - done:

![image](https://cloud.githubusercontent.com/assets/633862/17021304/78d9a98a-4f47-11e6-88d2-7791ee9ac74b.png)

**Comment by billinghamj** [comment]
Appreciated 👍
