### ISSUE TITLE
Travis CI setup - help please!

### ISSUE THREAD

**Issue by billinghamj** [jsonmodel/jsonmodel#507]
I have taken the initial steps to set up Travis, but have not managed to get it working yet. If you know how to get it working, please PR :)

https://travis-ci.org/jsonmodel/jsonmodel/builds/143750604

**Comment by icanzilb** [comment]
I think that the repo still features the original xcode project - if you're setting CI I guess it's best to create a new xcode demo app with a proper test target, etc. Just an idea :)

**Comment by billinghamj** [comment]
I did recreate the entire project from scratch actually - it tests nicely on my computer. Seems that there is something wrong with the scheme file though.
