### ISSUE TITLE
Error because of an empty NSArray instead of NSDictionary

### ISSUE THREAD

**Issue by x128** [jsonmodel/jsonmodel#508]
I'm trying to initWithData/initWithString with the following server response: `{"result":"error","data":[],"message":"Some important message to the user"}`

The server response is not correct. The model's `data` property is marked as optional, its type is my custom class (another `JSONModel` child).

In `__importDictionary:withKeyMapper:validation:error:`, on line `JSONModel.m:294`, the `jsonValue` is assigned a string (a string!!) `@"0 elements"`. Then of course it fails to initialize: _Attempt to initialize JSONModel object using initWithDictionary:error: but the dictionary parameter was not an 'NSDictionary'._

So, the whole object fails to initialize, though the problem is with an empty optional property. I would consider another check, something like that, I don't think it's very excessive:

```
@@ -371,7 +371,7 @@ static JSONKeyMapper* globalKeyMapper = nil;
                 JSONModelError* initErr = nil;
                 id value = [[property.type alloc] initWithDictionary: jsonValue error:&initErr];
 
-                if (!value) {
+                if (!value || [jsonValue isEqual:@"0 elements"]) {
                     //skip this property, continue with next property
                     if (property.isOptional || !validation) continue;
```

I understand that it's a bug on the server side, but this seems to be a popular bug; other parsers (e.g. AFNetworking) successfully deal with this, assigning `nil`.

**Comment by billinghamj** [comment]
JSONModel is only intended to deserialize from JSON into an exactly equivalent set of Obj-C objects. It is not intended to coerce/correct/fix the JSON. Doing so is out of scope I'm afraid.

That being said, there are still lots of ways you can work around this issue. I would probably recommend having the `data` property be the `NSObject` type, with custom setters to handle various different types of input.
