### ISSUE TITLE
Readme tutorial links broken

### ISSUE THREAD

**Issue by boezerooij** [jsonmodel/jsonmodel#511]
Hi, thanks for this awesome repo, it's gonna save me a lot of time.

Could you please update the links to the tutorials in the README.md, they don't seem to work anymore:

```
Step-by-step tutorials:
How to fetch and parse JSON by using data models
Performance optimisation for working with JSON feeds via JSONModel
How to make a YouTube app using MGBox and JSONModel
```

**Comment by icanzilb** [comment]
Those are hosted one of my web sites, and my server has been under attack for a week and I still haven't recovered all domains - should be back online by next week.

**Comment by billinghamj** [comment]
We could try moving some of the content into a wiki hosted by GitHub instead potentially.

**Comment by icanzilb** [comment]
Also a nice idea

**Comment by billinghamj** [comment]
Links removed for now
