### ISSUE TITLE
How to get the origin json dictionary from a json model?

### ISSUE THREAD

**Issue by Whirlwind** [jsonmodel/jsonmodel#513]
I have a dictionary and a model, but the properties is not all in the model. So I have pick some value for the origin json dictionary.

I read the source code, but it seem not store the origin json dictionary.

**Comment by billinghamj** [comment]
You're correct - JSONModel does not store the original dictionary after deserialization has taken place.

If you need access to the original dictionary, you can just keep a copy of the original NSData/NSString/NSDictionary which you had prior to deserialization.
