### ISSUE TITLE
XCode 8 + iOS 10 Beta 3 - JSONModel throwing an error

### ISSUE THREAD

**Issue by Sdaswani** [jsonmodel/jsonmodel#514]
I'm deploying an app using XCode 8 onto an iOS 10 Beta 3 iPhone 5, and a call to JSONModel that usually works is failing with the following error:

Error Domain=JSONModelErrorDomain Code=1 "Invalid JSON data. Required JSON keys are missing from the input. Check the error user information." UserInfo={kJSONModelMissingKeys=(
    tokens
), NSLocalizedDescription=Invalid JSON data. Required JSON keys are missing from the input. Check the error user information.}

I know for a fact this call works on older iOSes / XCodes, and if I modify the JSONModel initWithDictionary method to not return nil, everything works. I believe this is the first error that is returning nil:

```
    //check incoming data structure
    if (![self __doesDictionary:dict matchModelWithKeyMapper:self.__keyMapper error:err]) {
        return nil;
    } 
```

**Comment by billinghamj** [comment]
Please also provide a copy of the model and JSON you're deserializing

**Comment by icanzilb** [comment]
you're deploying an app on iOS10? I thought that's not out for another few months?

**Comment by Sdaswani** [comment]
@icanzilb we are regression testing our app on iOS 10 Beta 3 - I don't want it to drop (current guess is early September) and not have our app work ;) .

@billinghamj will do.

**Comment by Sdaswani** [comment]
@billinghamj I'm going to email you personally, would rather not have our model and response in the public. Please don't distribute either (nothing contractual, just appreciate your consideration ;) ).

**Comment by icanzilb** [comment]
@billinghamj be sure to charge a good hourly rate for private consultancy 👍

**Comment by billinghamj** [comment]
@Sdaswani Sorry - no can do. This is a public open source project. If you want free support on it, you need to work along the same lines.

I don't necessarily need the actual original model & JSON. Just provide the smallest set of JSON and model code which exhibits the problem, so I can reproduce it. All the property names, etc. can be different.

**Comment by Sdaswani** [comment]
I'm going to check our server to make sure this isn't an issue on my side.
