### ISSUE TITLE
Model cascading (models including other models)

### ISSUE THREAD

**Issue by rchampa** [jsonmodel/jsonmodel#515]
I'm using the same example on the web

OrderModel.h

    @protocol ProductModel
    @end
    
    @interface ProductModel : JSONModel
    @property (assign, nonatomic) int id;
    @property (strong, nonatomic) NSString* name;
    @property (assign, nonatomic) float price;
    @end
    
    @implementation ProductModel
    @end
    
    @interface OrderModel : JSONModel
    @property (assign, nonatomic) int order_id;
    @property (assign, nonatomic) float total_price;
    @property (strong, nonatomic) NSArray<ProductModel>* products;
    @end
    
    @implementation OrderModel
    @end

But when I build the project I face one issue "Duplicate symbols" 

    duplicate symbol _OBJC_CLASS_$_OrderModel
    ld: 576 duplicate symbols for architecture arm64
    clang: error: linker command failed with exit code 1

**Comment by billinghamj** [comment]
This issue is not related to JSONModel. There is most likely something wrong with how you're defining and/or importing these classes.
