### ISSUE TITLE
jsonmodel copy error

### ISSUE THREAD

**Issue by yituwangpeng** [jsonmodel/jsonmodel#516]
I have a class PLTravelCostsModel,it has tow properties.

```objc
@interface PLTravelCostsModel : JSONModel
@property (nonatomic, assign) double memberTotalSpendRMB;
@property (nonatomic, copy) NSString <Ignore> *memberCurrency;
@end
```

the "memberCurrency" is Ignore.

Now, the problem is:

- `A` is a Instance of `PLTravelCostsModel`
- `A.memberTotalSpendRMB == 200`
- `A.memberCurrency == @"CNY"`

if `PLTravelCostsModel *B = [A copy];`, the problem occurs:

- `B.memberTotalSpendRMB == 200`
- `B.memberCurrency == nil`

I dont't understand why?please help me.

**Comment by billinghamj** [comment]
JSONModel ignores all properties marked `Ignore`. If you need a copy to work with this property, you should override `copy` and ensure it is copied.
