### ISSUE TITLE
Property with name "init" cause validation failed

### ISSUE THREAD

**Issue by kientux** [jsonmodel/jsonmodel#517]
My JSON has a property named `init`. So my model failed to validate:

```
Model does not validate. The custom validation for the input data failed.
```

Is there any reason why a property named `init` can causes JSONModel to fail validation? Xcode does not allow a method start with `-initWith...` that doesn't return an instance type, but I don't see anything relate about that.

I changed my property name, used a custom key mapper and it worked but I just want to know why.

Sorry for my bad English.

**Comment by billinghamj** [comment]
This fundamentally conflicts with how Obj-C works. You can't define a property called `init` because that's an important function.

You could work around this by mapping from init in the raw JSON to something else in the Obj-C model.
