### ISSUE TITLE
JSONModelNetworking is deprectated

### ISSUE THREAD

**Issue by pikaboo** [jsonmodel/jsonmodel#519]
Why did you deprecate this part of the framework ?

**Comment by icanzilb** [comment]
it offered a very basic functionality and it probably did more harm than good (for example it didn't handle all edge cases of parameter encodings, did not handle edge cases in http response codes, it did not offer a way to cancel network operations and many other stuff). the right thing to do is to use a full fledged network framework, which will be well tested and will provide the latest security fixes, etc.
