### ISSUE TITLE
How to deal with enums?

### ISSUE THREAD

**Issue by kevinrenskers** [JSONModel/JSONModel#52]
Let's say my model has this enum property:

```
typedef enum {
    StatusOpen,
    StatusClosed,
} Status;

@property (nonatomic) Status status;
```

If the status in the JSON is a string ("open" or "closed"), how can I transform from the string to the enum? It seems that JSONValueTransformer categories won't be called if it's not an object. Right now I'm saving the status as a NSString, and created a getter that does the transforming into the enum, but it's a bit weird.

**Comment by zhunt11** [comment]
This appears to be broken in the latest version of JSONModel. Can anyone else confirm this? My -(void)set[Propertyname]With[ClassName] are no longer being called. Is there a workaround or a different way to handle turning strings into enums?

**Comment by zhunt11** [comment]
Figured it out. The new initWithModelToJSONDictionary: appears to have changed what the key/value pair is. The value is now the JSON property name and the key is now the name I give my property. The deprecated method, initWithDictionary:, was the other way around.

**Comment by billinghamj** [comment]
Indeed, the order was flipped and the old method deprecated for consistency.
