### ISSUE TITLE
I need help...

### ISSUE THREAD

**Issue by phyoo** [jsonmodel/jsonmodel#520]
`{
    "message": "ok",
    "status": "200",
    "result": {
        "pageSize": 15,
        "pageNo": 1,
        "rowCount": 2,
        "pageCount": 1,
        "pageSizeList": [
                         5,
                         10,
                         30,
                         50,
                         100
                         ],
        "resultList": [
                       [
                        {
                        "id": 2,
                        "title": "2",
                        "type": "4",
                        "surplusCount": 2,
                        "startTime": 1512057600000,
                        "endTime": 1512057600000,
                        "price": 2,
                        "auditTime": 2,
                        },
                        {
                        "id": 5,
                        "memberId": 16,
                        "taskId": 2,
                        "status": 1
                        }
                        ],
                       ......
                       ]
    }
}	
`

`#import "MSTBaseModel.h"
@class MyTaskInfoModel;

@interface MyTaskModel : MSTBaseModel

@property(nonatomic, strong) MyTaskInfoModel *result;

@end

@interface MyTaskInfoModel : JSONModel

@property(nonatomic, copy) NSString *pageSize;
@property(nonatomic, copy) NSString *pageNo;
@property(nonatomic, copy) NSString *rowCount;
@property(nonatomic, copy) NSArray *pageSizeList;
@property(nonatomic, strong) NSArray<NSArray *> *resultList;

@end
`
how I go on?

**Comment by billinghamj** [comment]
You haven't provided enough information for us to diagnose this issue properly. Is the issue that the `resultList` isn't deserializing?

**Comment by phyoo** [comment]
uh, I don't how to deserialize the "resultList", how to do next? thx

**Comment by billinghamj** [comment]
JSONModel can't handle the deserialization of objects which are nested within two arrays. It only supports deserialization with one level of array.

If you make a custom setter, you can implement this yourself relatively easily:

```objc
- (void)setResultList:(NSArray *)resultList
{
  // set _resultList manually here
}
