### ISSUE TITLE
Obj-C issue with property/key name and 7digital API

### ISSUE THREAD

**Issue by quetool** [jsonmodel/jsonmodel#523]
I'm using the 7digital API that uses the word "release" in the key to identify the album.
The problem is I can not create a property called "release" because the compiler apparently being confused with the "release" directive.
Should I use the KeyMapper? In wich way? Thanks!

Image 1: The error
![captura de pantalla 2016-08-18 a las 13 30 00](https://cloud.githubusercontent.com/assets/14978705/17782142/904ccf04-6548-11e6-9b63-b02133e154c1.png)

Image 2: 7Digital API response
![captura de pantalla 2016-08-18 a las 13 32 26](https://cloud.githubusercontent.com/assets/14978705/17782189/c348bbb6-6548-11e6-9ddd-dc17e3cb0044.png)

**Comment by billinghamj** [comment]
Ah yes, this is fairly simple. First, change your property to be named some other way:

```objc
@property (strong, nonatomic) ReleaseModel<Optional> *releaseInfo;
```

Then add a keymapper in the implementation (.m) file:

```objc
+ (JSONKeyMapper *)keyMapper
{
  return [JSONKeyMapper mapper:[super keyMapper] withExceptions:@{
    @"release": @"releaseInfo"
  };
}
```

This should work pretty much as-is, but let me know if you have problems.

**Comment by quetool** [comment]
What is the difference with this?
(sorry I just found)

```
+(JSONKeyMapper *)keyMapper
{
    return [[JSONKeyMapper alloc] initWithDictionary:@{@"release": @"releaseInfo"}];
}
```

**Comment by billinghamj** [comment]
For that one, it'd need to be the other way around (sorry for the inconsistency - I will fix it):

```objc
+ (JSONKeyMapper *)keyMapper
{
  return [[JSONKeyMapper alloc] initWithDictionary:@{@"releaseInfo": @"release"}];
}
```

It will also work in this case, but if you have any other key-mappers, they will not be honored.

**Comment by billinghamj** [comment]
Sorry ignore the above, the code you wrote is correct.

**Comment by quetool** [comment]
Yes, i figured out right now! :P Thanks!
