### ISSUE TITLE
skip false BOOL values from serialisation

### ISSUE THREAD

**Issue by kamendo** [jsonmodel/jsonmodel#524]
I have a model with optional BOOLs, for example

```objc
@interface MyModel : JSONModel

@property (nonatomic) BOOL optionalBool1;

@end
```

I save the model to a file using toJSONString function.
To save disk space I want to skip all optional booleans which are false. 
I am planning to override toJSONString and traverse all my properties and see if they are optional and serialize only them - is this the best way to do it?

**Comment by billinghamj** [comment]
Assuming you want to keep using the type `BOOL`, yes - there is no other way to achieve this. However, you could alternatively do this:

```objc
@interface MyModel : JSONModel

@property (nonatomic) NSNumber <Optional> *optionalBool1;

@end
```

**Comment by billinghamj** [comment]
Also aside from specific JSONModel stuff - I'd caution that wanting to exclude `false` values for disk space reasons strongly sounds like excessive premature optimization:

- if the number of `false` values is relatively small, removing them won't make any meaningful difference to file size
- if the number of `false` values is significant, you will achieve drastically better space savings by simply gzipping/deflating the file before saving it

**Comment by kamendo** [comment]
Thank you for the comment. You are correct for the disk space optimization.
My motivation is that the user can open and view this file and I don't want to spam him with all this options that are false by default.
