### ISSUE TITLE
KeyMapper initWithJSONToModelBlock: modelToJSONBlock: crash when decode

### ISSUE THREAD

**Issue by jhgfer** [jsonmodel/jsonmodel#525]
_modelToJSONKeyBlock = ^NSString*(NSString* keyName) {
            
            //try to return cached transformed key
            if (myself.toJSONMap[keyName]) return myself.toJSONMap[keyName];
            
            //try to convert the key, and store in the cache
            NSString* result = toJSON(keyName);
            myself.toJSONMap[keyName] = result;
            return result;
            
        };
 myself.toJSONMap[keyName] = result; may cause a crash when decode JSONModel  objects at different thread. 
↓↓↓↓↓Crash Log ↓↓↓↓↓
> #0
Crashed: NSOperationQueue 0x1704386c0 :: NSOperation 0x17445d3d0
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x000000017d25beb8
 Raw Text
0	libobjc.A.dylib	
objc_msgSend + 16
1	CoreFoundation	
-[__NSDictionaryM objectForKey:] + 160
2	XXXX	
JSONKeyMapper.m line 59
__59-[JSONKeyMapper initWithJSONToModelBlock:modelToJSONBlock:]_block_invoke.13
3	XXXX	
JSONKeyMapper.m line 110
-[JSONKeyMapper convertValue:isImportingToModel:]
4	XXXX	
JSONModel.m line 270
-[JSONModel __mapString:withKeyMapper:importing:]
5	XXXX	
JSONModel.m line 226
-[JSONModel __doesDictionary:matchModelWithKeyMapper:error:]
6	XXXX	
JSONModel.m line 186
-[JSONModel initWithDictionary:error:]
7	XXXX	
XXXBaseModel.m line 22

Thank you

**Comment by billinghamj** [comment]
Ah I think I will just remove this caching optimisation. These days it probably brings very little benefit - if any.

**Comment by billinghamj** [comment]
You're using a very old version of JSONModel. Please make sure to update to the latest version.
