### ISSUE TITLE
Issue on iPhone 5

### ISSUE THREAD

**Issue by quetool** [jsonmodel/jsonmodel#529]
Hi, i'm having an issue only in iPhone 5

I will try to explaine with my poor english :P

I am filling an NSMutableArray "arrayCanciones" with TrackModels (JSONModel) in this way:

![captura de pantalla 2016-08-31 a las 10 33 36](https://cloud.githubusercontent.com/assets/14978705/18130908/435a8f28-6f67-11e6-96dd-687bf8231bd4.png)

Then, i want to pass one object of that array to a method in appDelegate, like this:

![captura de pantalla 2016-08-31 a las 10 37 03](https://cloud.githubusercontent.com/assets/14978705/18130977/788dc386-6f67-11e6-9c84-54816eb7294e.png)

(As you see, TrackModel *track is not showing key/values inside and this is happening only in iPhone 5)

And this is where the code is broken in JSONModel.m

![captura de pantalla 2016-08-31 a las 10 21 01](https://cloud.githubusercontent.com/assets/14978705/18131087/e0f78510-6f67-11e6-805e-c53a73c1ce46.png)

As example and a way to help to understand, this is how it see TrackModel *track in iPhone 6S:

![captura de pantalla 2016-08-31 a las 10 37 22](https://cloud.githubusercontent.com/assets/14978705/18131127/1167ad92-6f68-11e6-854d-79a9c7a6e6c3.png)

I don't know why but, like i said, this is happening only in iPhone 5

**Comment by billinghamj** [comment]
Hmm could be an issue with 32/64 bit. The iPhone 5s was the first one with a 64-bit processor.

**Comment by billinghamj** [comment]
Could you provide the JSON, model code, and the code you're deserializing with - as text please? This will make it easier for us to debug.

**Comment by quetool** [comment]
I hope this is what you want:

Like before, this is where i fill the NSMutableArray with the TrackModels

```
NSMutableDictionary *objeto = [[results objectAtIndex:i] mutableCopy];
NSError *error;
NSData *dataStore = [NSJSONSerialization dataWithJSONObject:objeto options:NSJSONWritingPrettyPrinted error:&error];
NSString *stringStore = [[NSString alloc] initWithData:dataStore encoding:NSUTF8StringEncoding];
TrackModel *track = [[TrackModel alloc] initWithString:stringStore error:&error];
[arrayCanciones addObject:track];
```

stringStore is a JSON string
Printing description of stringStore:

```
{
  "id" : 32793930,
  "discNumber" : 1,
  "version" : "Original",
  "trackNumber" : 1,
  "release" : {
    "id" : 3080692,
    "label" : {
      "id" : 260271,
      "name" : "Jwa Jazz Records"
    },
    "version" : "",
    "addedDateSpecified" : false,
    "licensor" : {
      "id" : 310,
      "name" : "CD Baby"
    },
    "type" : "Album",
    "title" : "Fantango",
    "barcode" : "859705054258",
    "explicitContent" : false,
    "image" : "http:\/\/artwork-cdn.7static.com\/static\/img\/sleeveart\/00\/030\/806\/0003080692_50.jpg",
    "slug" : "fantango",
    "duration" : 0,
    "artist" : {
      "id" : 2070858,
      "appearsAs" : "Tango Extremo",
      "slug" : "tango-extremo",
      "name" : "Tango Extremo",
      "image" : "http:\/\/artwork-cdn.7static.com\/static\/img\/artistimages\/00\/020\/708\/0002070858_150.jpg",
      "isPlaceholderImage" : true
    }
  },
  "popularity" : 0.1,
  "subscriptionStreaming" : {
    "releaseDate" : "2013-12-12T00:00:00Z"
  },
  "type" : "Audio",
  "title" : "Milonga de Mis Amores",
  "explicitContent" : false,
  "isrc" : "TCAAT1066128",
  "number" : 1,
  "duration" : 147,
  "artist" : {
    "id" : 2070858,
    "appearsAs" : "Tango Extremo",
    "slug" : "tango-extremo",
    "name" : "Tango Extremo",
    "image" : "http:\/\/artwork-cdn.7static.com\/static\/img\/artistimages\/00\/020\/708\/0002070858_150.jpg",
    "isPlaceholderImage" : true
  }
}
```

This is TrackModel.h

```
#import "JSONModel.h"

@interface TrackModel : JSONModel

@property (strong, nonatomic) NSString<Optional> *adSupportedStreaming;
@property (strong, nonatomic) NSString<Optional> *addedDate;
@property (assign, nonatomic) NSNumber<Optional> *barcode;
@property (strong, nonatomic) NSString<Optional> *download;
@property (assign, nonatomic) NSNumber<Optional> *duration;
@property (assign, nonatomic) NSNumber<Optional> *explicitContent;
@property (strong, nonatomic) NSString<Optional> *formats;
@property (assign, nonatomic) int id;
@property (strong, nonatomic) NSString<Optional> *image;
//@property (strong, nonatomic) NSString<Optional> *kind;
@property (strong, nonatomic) NSString<Optional> *popularity;
@property (strong, nonatomic) NSString<Optional> *price;
@property (strong, nonatomic) NSString<Optional> *releaseDate;
@property (strong, nonatomic) NSString<Optional> *slug;
@property (strong, nonatomic) NSString<Optional> *title;
@property (assign, nonatomic) NSNumber<Optional> *trackCount;
@property (strong, nonatomic) NSString<Optional> *type;
@property (strong, nonatomic) NSString<Optional> *url;
@property (strong, nonatomic) NSString<Optional> *version;
//@property (strong, nonatomic) NSString<Optional> *wrapperType;
@property (assign, nonatomic) NSNumber<Optional> *year;

@property (strong, nonatomic) ArtistModel<Optional> *ModeloArtista;
@property (strong, nonatomic) ReleaseModel<Optional> *ModeloRelease;

@property (assign, nonatomic) NSNumber<Optional> *discNumber;
@property (strong, nonatomic) NSString<Optional> *isrc;
@property (assign, nonatomic) NSNumber<Optional> *number;
@property (assign, nonatomic) NSNumber<Optional> *trackNumber;

@end

```

This is TrackModel.m
```
#import "TrackModel.h"

@implementation TrackModel

+(JSONKeyMapper *)keyMapper
{
    return [[JSONKeyMapper alloc] initWithDictionary:@{@"artist": @"ModeloArtista",
                                                       @"release": @"ModeloRelease"}];
}

@end
```

**Comment by billinghamj** [comment]
Perfect - thanks

**Comment by billinghamj** [comment]
If you change the `id` property to an `NSNumber`, does it work then?

**Comment by billinghamj** [comment]
I suspect you might just need to change it from `int` to `NSInteger`, but it'd be interesting to see how `NSNumber` worked too

**Comment by quetool** [comment]
I tried both and i am having the same issue.

**Comment by quetool** [comment]
I don't know if is it a coincidence but this is what i am seeing:

if i do this way:
![captura de pantalla 2016-08-31 a las 11 46 59](https://cloud.githubusercontent.com/assets/14978705/18133382/c6432bc6-6f70-11e6-9b6d-e6fa1ac03502.png)


i am getting an exception here:
![captura de pantalla 2016-08-31 a las 11 46 12](https://cloud.githubusercontent.com/assets/14978705/18133400/d24a18bc-6f70-11e6-8a48-cb409ea3d8ce.png)

if i do this way:
![captura de pantalla 2016-08-31 a las 11 41 33](https://cloud.githubusercontent.com/assets/14978705/18133414/df42ceec-6f70-11e6-820b-aa5019850aef.png)

i am getting an exception here:
![captura de pantalla 2016-08-31 a las 11 41 18](https://cloud.githubusercontent.com/assets/14978705/18133429/f073b92e-6f70-11e6-9a0c-395c7429a17a.png)

Always broke on "barcode" key. Like i say, may be is a coincidence, but if it helps....

**Comment by quetool** [comment]
Ok, i solved it:
Like you said, the problem is in the data types.
I changed all properties to NSString and it works

```
#import "JSONModel.h"

@interface TrackModel : JSONModel

@property NSInteger id;
@property (strong, nonatomic) NSString<Optional> *adSupportedStreaming;
@property (strong, nonatomic) NSString<Optional> *addedDate;
@property (strong, nonatomic) NSString<Optional> *barcode;
@property (strong, nonatomic) NSString<Optional> *download;
@property (strong, nonatomic) NSString<Optional> *duration;
@property (strong, nonatomic) NSString<Optional> *explicitContent;
@property (strong, nonatomic) NSString<Optional> *formats;
@property (strong, nonatomic) NSString<Optional> *image;
@property (strong, nonatomic) NSString<Optional> *popularity;
@property (strong, nonatomic) NSString<Optional> *price;
@property (strong, nonatomic) NSString<Optional> *releaseDate;
@property (strong, nonatomic) NSString<Optional> *slug;
@property (strong, nonatomic) NSString<Optional> *title;
@property (strong, nonatomic) NSString<Optional> *trackCount;
@property (strong, nonatomic) NSString<Optional> *type;
@property (strong, nonatomic) NSString<Optional> *url;
@property (strong, nonatomic) NSString<Optional> *version;
@property (strong, nonatomic) NSString<Optional> *year;
@property (strong, nonatomic) NSString<Optional> *discNumber;
@property (strong, nonatomic) NSString<Optional> *isrc;
@property (strong, nonatomic) NSString<Optional> *number;
@property (strong, nonatomic) NSString<Optional> *trackNumber;
@property ArtistModel<Optional> *ModeloArtista;
@property ReleaseModel<Optional> *ModeloRelease;

@end
```

**Comment by billinghamj** [comment]
Hmm that's a little weird. It might be that the mapping from property flags to types is incorrect, but it's quite hard to determine really. I also don't have the required devices for testing.

**Comment by quetool** [comment]
Ok, for the moment is solved, i do not have problems if i parse everything like string. I will advise you in case of future problems.

**Comment by robinzhangx** [comment]
Hi @quetool, the problem is using ```assign``` with ```NSNumber```. ```assign``` won't retain the object. When the object is freed later, you will get a dangling pointer and see the crash if you try to access it. I think you want ```strong``` in your model.

**Comment by billinghamj** [comment]
Ah, yes. I didn't see that. Surprised the compiler didn't flag that as an error.

If you simply remove assign/strong, it will default to safe values.

**Comment by quetool** [comment]
thanks to both!
