### ISSUE TITLE
initWithModelToJSONDictionary

### ISSUE THREAD

**Issue by quetool** [jsonmodel/jsonmodel#530]
Hi, i saw in example in the readme file a function named initWithModelToJSONDictionary. Where is it? is it deprecated?

**Comment by billinghamj** [comment]
Nope that should be fine.

**Comment by billinghamj** [comment]
Perhaps you need to use an equivalent with the error output though?

**Comment by quetool** [comment]
I do not have initWithModelToJSONDictionary

![captura de pantalla 2016-09-05 a las 10 10 02](https://cloud.githubusercontent.com/assets/14978705/18248815/f93c2d6e-7350-11e6-8e9a-7b2060949dfb.png)

is there an update that i missed?

**Comment by billinghamj** [comment]
Just upgrade JSONModel to the latest version - 1.4.0

**Comment by quetool** [comment]
Thanks, that was right. I was convinced I had the latest version :S
