### ISSUE TITLE
JSONKeyMapper

### ISSUE THREAD

**Issue by hanzhuzi** [jsonmodel/jsonmodel#531]
I could find an error, I user example 

```objc
+(JSONKeyMapper*)keyMapper
{
  return [[JSONKeyMapper alloc] initWithModelToJSONDictionary:@{
    @"id": @"order_id",
    @"productName": @"order_details.name",
    @"price": @"order_details.price.usd"
  }];
}
```

I get nil, but I use

```objc
+(JSONKeyMapper*)keyMapper
{
  return [[JSONKeyMapper alloc] initWithModelToJSONDictionary:@{
   @"order_id" : @"id",
    @"order_details.name" : @"productName",
    @"order_details.price.usd" : @"price"
  }];
}
```

is good.

**Comment by billinghamj** [comment]
Please provide the JSON, the model class, and the code you're running

**Comment by johncpang** [comment]
@hanzhuzi, you are right. The key of dictionary (left side) is the path to the JSON value, with dots means sub-object. The value of dictionary (right side) is the preferred variable/member's name.  A variable/member's name, definitely, has no dots.

**Comment by billinghamj** [comment]
That is not how it is supposed to work. The keys should be the model property names - containing no dots. The values should be the JSON key paths, which can include dots.

I thought I tested this pretty extensively, but perhaps made a mistake somehow.

**Comment by johncpang** [comment]
I think it's mistake in doc rather than in code.  See the documentation in [JSONKeyMapper.h](https://github.com/jsonmodel/jsonmodel/blob/master/JSONModel/JSONModelTransformations/JSONKeyMapper.h)

 If you need custom mapping it's as easy as:
```
 + (JSONKeyMapper *)keyMapper {
 return [[JSONKeyMapper alloc] initWithDictionary:@{@"crazy_JSON_name":@"myCamelCaseName"}];
 }
```

key = crazy_JSON_name
value = myCamelCaseName

**Comment by billinghamj** [comment]
The above method has now been deprecated in the latest version (v1.4)

**Comment by hanzhuzi** [comment]
oh, thanks

**Comment by hanzhuzi** [comment]
@johncpang  thank you very much!

**Comment by hanzhuzi** [comment]
@billinghamj   may be I use JSONModel is old version, I could to see JSONModel latest version, thank you very much!

**Comment by billinghamj** [comment]
Yeah I'm pretty sure it could only be a mapping of model->JSON - see: https://github.com/jsonmodel/jsonmodel/blob/master/JSONModel/JSONModelTransformations/JSONKeyMapper.m#L83-L94

Additionally, the only method you should use for this is `initWithModelToJSONDictionary:`.

If you're using `initWithModelToJSONDictionary:` on v1.4, and you find that a model->JSON mapping is not working, please open a new issue providing the JSON, model class, and the code you're running :)
