### ISSUE TITLE
Process/Document JSON that is a Top-Level Array

### ISSUE THREAD

**Issue by ZaBlanc** [jsonmodel/jsonmodel#537]
It's unclear how to, if possible, process JSON that looks like this:

[
    { ... },    { ... },    { ... }
]

Is a top-level array possible to process?

**Comment by billinghamj** [comment]
Yup! Check out these methods :) https://github.com/jsonmodel/jsonmodel/blob/master/JSONModel/JSONModel/JSONModel.h#L194-L199
