### ISSUE TITLE
JSONHTTPCLIENT DEPRECATED IN LATEST RELEASE

### ISSUE THREAD

**Issue by yogesh2209** [jsonmodel/jsonmodel#542]
JSONHTTPClient is deprecated in your latest release.
POSTJSONFROMURLWITHSTRING also deprecated. Please tell me what to do. URGENT!

**Comment by billinghamj** [comment]
All JSONModel networking has been deprecated since v1.3.0 back in July.

Consider using `NSURLSession` or another library like `AFNetworking` instead.
