### ISSUE TITLE
Custom setters for object : ignore if no matching type

### ISSUE THREAD

**Issue by smidaharoun** [jsonmodel/jsonmodel#544]
Is it possible to ignore object if the type is not matching the one of the object.
Suppose we have this property : 

`@property (nonatomic) NSString <Optional> *videoUrl;`

What I want if the json contient a value with key `videoUrl` and its type is `NSString`, retrieve its value. Else if it's not an `NSString`,  ignore it.

**Comment by billinghamj** [comment]
Hmm this is a difficult one because it conflicts with one of JSONModel's core value propositions - performing the validation steps for you automatically.

In this instance, I'd advise flagging the property with `<Ignore>`, then overriding the initialization, as follows:

```objc
- (instancetype)initWithDictionary:(NSDictionary *)dict error:(NSError **)error
{
  if (!(self = [super initWithDictionary:dict error:error]))
    return nil;

  if ([dict[@"videoUrl"] isKindOfClass:[NSString class]])
    _videoUrl = dict[@"videoUrl"];

  return self;
}
```

**Comment by billinghamj** [comment]
That being said, I think a better solution could be something like this:

```objc
- (void)setVideoUrlWithJSONObject:(id)jsonObject
{
}
```

**Comment by billinghamj** [comment]
Any opinions @smidaharoun?

**Comment by smidaharoun** [comment]
Sorry about the late, 
I've just tested the setter in your last comment, The problem is that the setter is not called when getting the value of the property, It throws an exception `Type not allowed ` and when I log the property at this point, here what I get
`@property NSString* videoUrl (Optional, Standard JSON type, Setters = [])`
As you can see, the setters array is empty

**Comment by billinghamj** [comment]
@smidaharoun The latter example does not currently exist and is not currently supported. I'm just suggesting that it _could_ be a better solution to the problem. What is your opinion on that?

**Comment by smidaharoun** [comment]
I think it would be better if we had a setter like that. I think that way you would define only one setter and get all the job done within it. Better than having many setter and defining one for each type.

**Comment by billinghamj** [comment]
Okay I'll add that. In terms of finding the relevant setter, the most specific one will "win". e.g. if you had both `setVideoUrlWithJSONObject` and `setVideoUrlWithNSString`. The `NSString` type would use the latter, the `NSDictionary` type would be the former.

**Comment by billinghamj** [comment]
Added in v1.7.0

**Comment by smidaharoun** [comment]
Thanks a lot.
Keep up the good work @billinghamj
