### ISSUE TITLE
Nullability

### ISSUE THREAD

**Issue by alexiosdev** [jsonmodel/jsonmodel#548]
Is it possible that I can use objective-c nullability keywords when defining `JSONModel` subclasses?

I have some issues for nullability. 

This is example

```Objective-C
@protocol CIECarShortDetails
@end

@interface CIECarShortDetails : JSONModel

@property (strong, atomic) NSNumber						*adId;
@property (strong, atomic) NSString						*regYear;
...
@property (strong, atomic) NSString<Optional>			*variant;
...
@property (strong, atomic) CIEImageGallery<Optional>	*images;

@end
```
From swift3, implicitly unwrapped optionals are handled differently with previous versions as Apple explained in  [What's new in Swift](https://developer.apple.com/videos/play/wwdc2016/402/)

Since there's no nullability attribute assigned in the code above, I started to have weired issues from Swift3.

For example I use

```Swift
let car:CIECarShotDetails = ...    // Assume car is correctly initialized from JSON

someLabel.text = "Car Info : \(car.regYear) ..."
```

The content of `someLabel` looked like **"Car Info : 2012"** before but now it is showing **"Car Info : Optional(2012)"** because `regYear` is `String!` type.

Of course I can try `someLabel.text = "Car Info : " + car.regYear` but there seems to be many places doing like this and I don't want to get my hands dirty if possible.

I checked around the initialization code for a JSONModel instance in this library to see how it deals with optional and required values and make sure properties with out `<Optional>` is `non-nil` after successful initialization.

What about if I do something like this?  (To make Swift3 clear about nullability of properties in Objective-C class)

```Objective-C
NS_ASSUME_NONNULL_BEGIN
@protocol CIECarShortDetails
@end

@interface CIECarShortDetails : JSONModel

@property (strong, atomic) NSNumber						*adId;
@property (strong, atomic) NSString						*regYear;
...
@property (strong, atomic, nullable) NSString<Optional>			*variant;
...
@property (strong, atomic, nullable) CIEImageGallery<Optional>	*images;

@end
NS_ASSUME_NONNULL_END
```

One more question is that how is the optional array initialized?

```
@property (strong, atomic) NSArray<CIEModel,Optional>	*models;
```

Will it be `nil` or empty array when "models" key is not present in  JSON object?  

 If `nil` I think I can define like this.
```
@property (strong, atomic, nullable) NSArray<CIEModel,Optional>	*models;
```

It will be appreciated
- If any issue is duplicated and already closed.
- Give me suggestion if I am doing right or wrong, or what can be other solutions.

**Comment by billinghamj** [comment]
The new Obj-C syntax to support Swift should be combined with the JSONModel protocol notation.

New Obj-C syntax:

```objc
@property (nonatomic, nullable) NSString *someString;
@property (nonatomic, nonnull) NSNumber *someNumber;
@property (nonatomic, nonnull) NSArray <MyClass *> *someArray;
```

JSONModel syntax:

```objc
@protocol MyClass;

@property (nonatomic) NSString <Optional> *someString;
@property (nonatomic) NSNumber *someNumber;
@property (nonatomic) NSArray <MyClass> *someArray;
```

Combined:

```objc
@protocol MyClass;

@property (nonatomic, nullable) NSString <Optional> *someString;
@property (nonatomic, nonnull) NSNumber *someNumber;
@property (nonatomic, nonnull) NSArray <MyClass *> <MyClass> *someArray;
```

Does that answer your question?

**Comment by alexiosdev** [comment]
Thank you, @billinghamj  we can omit `nonnull` when use `NS_ASSUME_NONNULL_BEGIN` and `NS_ASSUME_NONNULL_END` macro.

**Comment by billinghamj** [comment]
Also worth noting: you can make JSONModel work with just the new Obj-C syntax without the JSONModel protocol notation by implementing two methods in the implementation file:

- `+ (BOOL)propertyIsOptional:(NSString *)propertyName;`
- `+ (Class)classForCollectionProperty:(NSString *)propertyName;`

**Comment by billinghamj** [comment]
No worries. Was just trying to be specific/explicit with the `nonnull` references. 

Just comment again if you need this to be reopened.

**Comment by alexiosdev** [comment]
When I marked optional members as `nonnull`, I got bunch of errors on my swift code because I had to add appropriate `?` or '!'  😄 .    Became more pain but is a way to become more type safe.
