### ISSUE TITLE
BOOL from NSNumber custom setter not working

### ISSUE THREAD

**Issue by igorcarrasco** [jsonmodel/jsonmodel#549]
@interface PhoneModel : JSONModel
@property (nonatomic) NSString* deviceName;
@property (nonatomic) BOOL SNRState;
@end

@implementation PhoneModel
+ (JSONKeyMapper *)keyMapper
{
    return [[JSONKeyMapper alloc] initWithModelToJSONDictionary:@{
                                                              @"deviceName": @"RemoteDestinationName",
                                                              @"SNRState": @"IsSNREnabled"
                                                              }];
}
- (void)setSNRStateWithNSNumber:(NSNumber *)number
{
    self.SNRState = [number boolValue];
}

@end

What happens in code:
[myobject valueForKey:@"SNRState"] still returns 0 or 1 and not true/yes or false/no.
I used a breakpoint to make sure the custom setter setSNRStateWithNSNumber was called and it was.
Any idea why why it returns 0/1 and not false/true?

I also tried a custom getter but for some reason it was always return NO because it was nil.

**Comment by billinghamj** [comment]
`BOOL` is implemented as 0/1 under-the-hood.

See: http://opensource.apple.com/source/objc4/objc4-680/runtime/objc.h

**Comment by igorcarrasco** [comment]
I see.
But I need it to return YES/true or NO/false.
How should I do it?

**Comment by billinghamj** [comment]
In the code, `1` is equal to `YES`/`true` and `0` is equal to `NO`/`false`. If you need those as a string, you could do:

`val ? @"YES" : @"NO"`
