### ISSUE TITLE
Confusion on root model if no name given

### ISSUE THREAD

**Issue by acenario** [JSONModel/JSONModel#55]
Hi,

I love your project, it makes JSON parsing so much simpler! I have a question though, how would I handle a JSON document that has no name associated? This is the entire document I am dealing with.

```
{
"class_id": "ADVMTG-1",
"class_pk": 10293,
"course": "Advisor Meeting",
"course_id": 7,
"course_type": "Advisory",
"description": "ADV: Abreu, E",
"group_fk": 13945,
"primary_grade_level": "None",
"school_level": "Upper School",
"school_year": 2012,
"status": "Active",
"subject": "Administration",
"teacher_fk": 393,
"teacher_full_name": "Eleodoro Abreu",
"update_date": "2012-10-23T10:06:00-05:00",
"teachers": [
    {
        "person_fk": 393,
        "role": "Primary Teacher",
        "role_id": 1,
        "teacher_name": "Eleodoro Abreu",
        "update_grades": true,
        "view_grades": true
    }
],
"meeting_times": [
    {
        "block": "Advisor Meetings",
        "block_abbreviation": "ADV",
        "day": "Friday",
        "end_time": null,
        "grading_period": "ALL",
        "room": null,
        "start_time": null
    }
]
```

}

By name associated I mean how "paging" below would be the root model:

```
{
"paging": {
    "page": 1,
    "total": 2931,
    "page_size": 20,
    "pages": 147
}
```

**Comment by RajanMaheshwari** [comment]
What if the root is an array and there is no name given to it. How it can be parsed
Example
[
  {
    "cik": "0001437719",
    "name": "10-4 CORP",
    "display_name": "10-4 Corp",
    "symbol": null,
  },
  {
    "cik": "0001408597",
    "name": "11 GOOD ENERGY INC",
    "display_name": "11 Good Energy Inc",
    "symbol": null,

  }
]

**Comment by maksumon** [comment]
You should use arrayOfModelsFromDictionaries: on your model class like so:

`NSArray* models = [YourModelClass arrayOfModelsFromDictionaries: objects];`

This will go over "objects" and convert each dictionary to a model and you get the result in models. If any item in objects fail to convert to model "models" will be nil.

**Comment by billinghamj** [comment]
Thanks @maksumon :+1:
