### ISSUE TITLE
duplicate definition JSONModel Property Compatibility

### ISSUE THREAD

**Issue by FlyingNoob** [jsonmodel/jsonmodel#552]
I use cocoa pods  'user_framework!'

so  I get the warning "duplicate definition JSONModel Property Compatibility"

**Comment by billinghamj** [comment]
https://github.com/jsonmodel/jsonmodel/blob/master/CONTRIBUTING.md#bugs

**Comment by billinghamj** [comment]
Open a new issue conforming to the contribution requirements and we'll get it fixed
