### ISSUE TITLE
can't use assign for Costume JsonModle Property 

### ISSUE THREAD

**Issue by AhmedShammala** [jsonmodel/jsonmodel#553]
hi 
i have problem take very long time searching and  i can't find solution i have Class name is "Product"
 have one Property name "lineItem" Type JsonModle 
<img width="471" alt="screen shot 2016-11-12 at 7 17 29 pm" src="https://cloud.githubusercontent.com/assets/11911318/20239622/2d5a965c-a90d-11e6-9fd2-b7cc035e3440.png">

now lineItem memory i want to be **assign** not **Strong** so i can change the value later without change previous instances !

if i make it Strong it's Cause a Crash like #439

**Comment by billinghamj** [comment]
This is not supported I'm afraid. If you want to ensure immutability of existing instances, you should explicitly copy them.
