### ISSUE TITLE
I think that some methods only need to be static, but not

### ISSUE THREAD

**Issue by caepek** [jsonmodel/jsonmodel#554]
like methods  "-(void)__inspectProperties" in class JSONModel？
If methods to be static, isn't that perform better?

**Comment by caepek** [comment]
That said, like "+(void)__inspectProperties"

**Comment by billinghamj** [comment]
They run in a static manner anyway - the results are cached. They may be changed to being truly static methods, but this would be dependent on #442

**Comment by caepek** [comment]
I also have another want to know that JSONModel will or not provide a optional one-one maping to DB , like a helper to FMDB just like the now association to networking[JSONModel+networking] in feature? Or have also existed the helper but I have not found？Could you help me?

**Comment by billinghamj** [comment]
No, JSONModel will not provide any kind of support for I/O

**Comment by caepek** [comment]
ok, I know, thanks very much!
