### ISSUE TITLE
How to handle the base class scernario.

### ISSUE THREAD

**Issue by harshadkhedekar** [jsonmodel/jsonmodel#556]
I have an entity class B which inherits from class A. For Eg @interface B : A . So for class A I have written as @interface A : JSONModel. But it is giving an error as EXCEPTION: Invalid type in JSON write (A) when I try to convert the object of class B to json string using toJSONString method.

**Comment by billinghamj** [comment]
https://github.com/jsonmodel/jsonmodel/blob/master/CONTRIBUTING.md#issues
