### ISSUE TITLE
Apple Mach-O Linker Error

### ISSUE THREAD

**Issue by jschoolcraft** [jsonmodel/jsonmodel#557]
Trying to use JSONModel in a project and was getting linker errors, created a sample project to demonstrate: https://github.com/jschoolcraft/JSONModelTest

This looks similar https://github.com/jsonmodel/jsonmodel/issues/288 but I've reproduced on two different machines with two different and new sample projects.  I'm not saying my cocoapods install isn't messed up on both machines, but I'm not seeing any other issues.

Showing Recent Messages
```
CompileC /Users/jschoolcraft/Library/Developer/Xcode/DerivedData/JSONModelTest-elbujcggedarftglqstyumeslyud/Build/Intermediates/JSONModelTest.build/Debug-iphonesimulator/JSONModelTest.build/Objects-normal/x86_64/ViewController.o JSONModelTest/ViewController.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/jschoolcraft/code/sandbox/JSONModelTest
    export LANG=en_US.US-ASCII
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_TodoModel", referenced from:
      objc-class-ref in ViewController.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```

**Comment by billinghamj** [comment]
This is not the same issue. `TodoModel` is a file within your project - not part of JSONModel. Most likely your `.m` file isn't set to be included in the target.

**Comment by jschoolcraft** [comment]
You're right.

For some reason I read the directions as "you don't need an implementation"
instead of "you just need an empty implementation".

On Tue, Dec 20, 2016 at 11:45 AM, James Billingham <notifications@github.com

**Comment by billinghamj** [comment]
Ahh yes, you always need an implementation for Objective-C classes - even if there is nothing in it. A relic from the C days I think :)
