### ISSUE TITLE
No support for macOS via Carthage

### ISSUE THREAD

**Issue by priya87** [jsonmodel/jsonmodel#562]
I tried to build jsonmodel via carthage for macOS but, there is no target for macOS.

**Comment by billinghamj** [comment]
Please open a PR to resolve this - then I will merge so you can use JSONModel through macOS with Carthage.

If possible please also resolve for tvOS & watchOS at the same time.

**Comment by priya87** [comment]
WIP

**Comment by priya87** [comment]
Submitted a PR.

**Comment by billinghamj** [comment]
This should now be resolved. Please close if so @priya87

**Comment by priya87** [comment]
It works. Thank you.
