### ISSUE TITLE
Example how to use with Swift 3

### ISSUE THREAD

**Issue by fvvliet** [jsonmodel/jsonmodel#566]
Could you please give an example how to use JSONModel with Swift 3.0 ? I read that I have to use classForCollectionProperty but I can't get it to work (XCode 8.2.1).

Thanks in advance
Frank

**Comment by billinghamj** [comment]
https://github.com/jsonmodel/jsonmodel/blob/9401793810521fab9ea0f1fedab3e92e672e3783/Examples/Tests/Models/Implementations/NestedModel.m
https://github.com/jsonmodel/jsonmodel/blob/9401793810521fab9ea0f1fedab3e92e672e3783/Examples/Tests/Models/Headers/NestedModel.h

**Comment by fvvliet** [comment]
Thank you @billinghamj for your reply... Actually I meant a Swift example instead of ObjC.

**Comment by billinghamj** [comment]
It should be exactly equivalent, but I actually don't know Swift.

Effectively, inherit your class from `JSONModel`, then implement the selector `classForCollectionProperty:` on the class level (not the instance - i.e. it needs to be static)

**Comment by fvvliet** [comment]
The classForCollectionProperty method gives the problem in Swift 3, the method name becomes "class(for...:)" and this generates a Swift error. 

NS_SWIFT_NAME should be added to this ObjC method

**Comment by billinghamj** [comment]
Most likely something like this:

```swift
class MyModel: JSONModel {
  class func classForCollectionProperty(propertyName: String) -> Class {
    switch (propertyName) {
      case "images":
        return ImageModel.class;
    }
  }
}
```

**Comment by billinghamj** [comment]
Ahh I see, because `class` is a keyword?

**Comment by fvvliet** [comment]
Yep

**Comment by billinghamj** [comment]
Can you PR this please?

**Comment by fvvliet** [comment]
Ok, will do. Might take a few days before I have time ;-)

**Comment by yogesh2209** [comment]
@fvvliet  Please help me ! Do you have any example of Jsonmodel in Swift ?
I have been using this library since last 2 years in my objective-c projects, but now, i want to use it in Swift. Please help.

**Comment by fvvliet** [comment]
Hello @yogesh2209, 
- you can use JSONModel with Swift 3 without a problem. Just put #import "JSONModel.h" in your ...-Bridging-Header.h file. When you then follow the code examples (translated to Swift syntax of course) all works fine.
- you can find my fix for the issue described above in file jsonmodel.h @ line 264, there is an example code snippet.

**Comment by yogesh2209** [comment]
Hi @fvvliet 

Thanks for the reply. It means a lot. I really appreciate that.

Link to sample JSON : http://elitify.com/products.json

Hi, I can't find the code example for Swift. 
Please help.
How to make it in Swift ?

I am attaching a demo json model project.
I have created products.swift and variants.swift (Please help me with products and variants file and most importantly how to get these values, i can make the rest of the model by myself.)
[jsonmodelTest.zip](https://github.com/jsonmodel/jsonmodel/files/973086/jsonmodelTest.zip)

**Comment by fvvliet** [comment]
Sorry, dont have much time but this might help you to get started 
[jsonmodelTest.zip](https://github.com/jsonmodel/jsonmodel/files/973202/jsonmodelTest.zip)
