### ISSUE TITLE
Build Failed: Redefinition of module JSONModel

### ISSUE THREAD

**Issue by Tawpie** [jsonmodel/jsonmodel#572]
environment: carthage 0.20.1 (and 0.18.x), and Xcode 8.3

repro:

1) clone repo locally
2) open JSONModel.xcodeproj
3) set scheme for iOS, SDK for iOS
4) build (fails)
Xcode points to module.modulemap as the place where redefinition occurs.

-or-

cart file contains: github "jsonmodel/JSONModel"
`carthage update --platform iOS`

```** BUILD FAILED **


The following build commands failed:
	CompileC /Users/<user>/Library/Caches/org.carthage.CarthageKit/DerivedData/JSONModel/1.7.0/Build/Intermediates/JSONModel.build/Release-iphoneos/JSONModel.build/Objects-normal/armv7/JSONModel+networking.o JSONModel/JSONModelNetworking/JSONModel+networking.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC /Users/<user>/Library/Caches/org.carthage.CarthageKit/DerivedData/JSONModel/1.7.0/Build/Intermediates/JSONModel.build/Release-iphoneos/JSONModel.build/Objects-normal/armv7/JSONAPI.o JSONModel/JSONModelNetworking/JSONAPI.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(2 failures)```

**Comment by jackrex** [comment]
same issue

**Comment by billinghamj** [comment]
I'm afraid I do not use, and am not able to support the use of Carthage. If you know how to fix this, please open a PR

**Comment by mingming1222** [comment]
hi, @billinghamj  please check this PR : #573

**Comment by billinghamj** [comment]
Thanks @mingming1222

@Tawpie @jackrex Could you confirm the above PR fixes this?

**Comment by domasn** [comment]
@billinghamj #573 works great 👍

**Comment by billinghamj** [comment]
Merged 👍

**Comment by domasn** [comment]
@billinghamj You need to tag the updated version for Carthage to pick it up ;)

**Comment by billinghamj** [comment]
Yeah I do need to do a release, can look at that in the next couple of days

**Comment by Tawpie** [comment]
Confirmed works with cartfile entry `github "jsonmodel/JSONModel" “master"`

**Comment by wangjoshuah** [comment]
@billinghamj Can you make a release on CocoaPods?
