### ISSUE TITLE
Support polymorphism when converting JSON models

### ISSUE THREAD

**Issue by candyleung1024** [jsonmodel/jsonmodel#574]
Let's say I've got classes like these:

```
@protocol Shape;

@interface MyAPIModel : JSONModel
@property NSArray<Shape> *shapes;
@end

@interface Shape : JSONModel
@property NSString *type;
@end

@interface Rectangle : Shape
@property NSInteger length;
@property NSInteger width;
@end

@interface Circle : Shape
@property NSInteger *radius;
@end
```

and the JSON for `MyAPIModel`:

```
{
  "shapes": [
    {
      "type": "rectangle",
      "length": 10,
      "width": 5
    },
    {
      "type": "circle",
      "radius": 8
    }
  ]
}
```

I would like to instantiate subclass objects according to the `type`, but currently only the superclass can be instantiated...

```
NSString *jsonStr = @"{\"shapes\":[{\"type\":\"rectangle\",\"length\":10,\"width\":5},{\"type\":\"circle\",\"radius\":8}]}";
MyAPIModel *api = [[MyAPIModel alloc] initWithString:jsonStr error:&error];
```

Is it possible to provide a method so that developers can determine which subclass to instantiate?

**Comment by candyleung1024** [comment]
The method would be something like this:

```
@interface JSONModel : NSObject

+ (Class)subclassForJSONValue:(NSDictionary *)dictionary

@end

@implementation JSONModel

+ (Class)subclassForJSONValue:(NSDictionary *)dictionary
{
    return self;
}

@end

@implementation Shape

+ (Class)subclassForJSONValue:(NSDictionary *)dictionary
{
    NSString *type = [dictionary objectForKey:@"type"];
    if (type && [type isKindOfClass:[NSString class]])
    {
        if ([type isEqualToString:@"rectangle"])
        {
            return [Rectangle class];
        }
        else if ([type isEqualToString:@"circle"])
        {
            return [Circle class];
        }
    }
    
    return self;
}

@end
```

so that we can decide which subclass to instantiate with the JSON value:

```
+(NSMutableArray*)arrayOfModelsFromDictionaries:(NSArray*)array error:(NSError**)err
{
    ...
    
    for (id d in array)
    {
        if ([d isKindOfClass:NSDictionary.class])
        {
            JSONModelError* initErr = nil;
            Class subclass = [self subclassForJSONValue:d];
            Class classToInstantiate = ([subclass isSubclassOfClass:self])? subclass : self;
            id obj = [[classToInstantiate alloc] initWithDictionary:d error:&initErr];
            ...
        }
        ...
    }
    
    ...
}
```

**Comment by billinghamj** [comment]
This is already completely possible with JSONModel - I have done so in a few projects. There has been some discussion in the past also.

I'm not sure whether I'd want to add further built-in support for this or not. If we do, it'll need to be with careful consideration and reasoning.

**Comment by billinghamj** [comment]
Currently this is best achieved by using a class cluster setup (like how Apple implements NSNumber under-the-hood). See this discussion: https://github.com/jsonmodel/jsonmodel/issues/229#issuecomment-52556421

**Comment by billinghamj** [comment]
Yeah having reviewed this, I think I am pretty comfortable with the way this currently works. However, I do think a lot of the more advanced use-cases of JSONModel need to be documented and explained better.

The current readme is not very extensive (which was intentional). I think it might be worth trimming the basic readme down to cover only the most basic cases, then have a folder showing a range of different use-cases in much more detail.

**Comment by candyleung1024** [comment]
Oh, thank you, looks like that's what I want, I'm going to try it out. And I think this one should definitely be documented. :)
