### ISSUE TITLE
Carthage not working

### ISSUE THREAD

**Issue by inigo333** [jsonmodel/jsonmodel#576]
Build is failing when running either
`$carthage update --platform iOS `
I also tried
`$carthage update --platform iOS --no-use-binaries `
as suggested in a stackoverflow question. However, I had the same result:

*** Fetching jsonmodel
*** Checking out jsonmodel at "1.7.0"
*** xcodebuild output can be found in /var/folders/tx/rp4f94cn3l796g97x6xv4d400000gn/T/carthage-xcodebuild.ZwuYbV.log
*** Building scheme "JSONModel" in JSONModel.xcodeproj
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/name/Library/Developer/Xcode/DerivedData/JSONModel-ahcpxzxnjollwnbaxethcepkowhj/Build/Intermediates/JSONModel.build/Release-iphoneos/JSONModel.build/Objects-normal/armv7/JSONHTTPClient.o JSONModel/JSONModelNetworking/JSONHTTPClient.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -project /Users/name/repo/project/Carthage/Checkouts/jsonmodel/JSONModel.xcodeproj -scheme JSONModel -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/name/Library/Developer/Xcode/DerivedData/JSONModel-ahcpxzxnjollwnbaxethcepkowhj/Build/Intermediates/JSONModel.build/Release-iphoneos/JSONModel.build/Objects-normal/armv7/JSONHTTPClient.o JSONModel/JSONModelNetworking/JSONHTTPClient.m normal armv7 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)

I'm attaching log file:

[carthage-xcodebuild.ZwuYbV.log.zip](https://github.com/jsonmodel/jsonmodel/files/882594/carthage-xcodebuild.ZwuYbV.log.zip)

**Comment by billinghamj** [comment]
#572
