### ISSUE TITLE
Using typed arrays of custom objects as a member

### ISSUE THREAD

**Issue by scihant** [jsonmodel/jsonmodel#577]
Is there a way to use a typed NSArray as a member in a JSONModel subclass ? 

In the current examples a model collection  is defined as a member like below:

`@property (nonatomic) NSArray <ProductModel> *products;`

What I want is the collection to be typed so that it can be seen as an array of `ProductModel`'s instead of `Any`'s from Swift code. In other words, I want to somehow define the member as shown below, without preventing the library from instantiating the correct classes automatically.

`@property (nonatomic) NSArray <ProductModel*> *products;`

This doesn't seem to be possible because the <> syntax cannot be used for both adding protocol conformance and type information at the same time. What would be the best way to have the same effect?

**Comment by bcse** [comment]
You can write
`@property (nonatomic) NSArray <ProductModel*> <ProductModel> *products;`

**Comment by scihant** [comment]
That was the first thing that I tried and it didn't compile. Turns out the cause of the problem was something else and not this line. It's working properly now. Thanks.
