### ISSUE TITLE
@throw in JSONModel file is Crashing the app

### ISSUE THREAD

**Issue by subham93** [jsonmodel/jsonmodel#578]
@throw [NSException exceptionWithName:@"JSONModelProperty type not allowed"
                                                  reason:[NSString stringWithFormat:@"Property type of %@.%@ is not supported by JSONModel.", self.class, p.name]
                                                 userInfo:nil];

-[__NSCFString charValue]: unrecognized selector sent to instance 0x14671810

This is crashing the app. There shouldn't be throw from your side. You can do NSLog or make this nil and proceed.

**Comment by billinghamj** [comment]
This throw is intentional. It should only happen if you, the developer, has made a mistake. In that scenario, it is correct for the whole app to crash.

**Comment by billinghamj** [comment]
That being said, the message being outputted does not look like that throw. Please provide some more information on exactly what's going wrong, in line with the instructions here: https://github.com/jsonmodel/jsonmodel/blob/master/CONTRIBUTING.md#bugs

**Comment by billinghamj** [comment]
If you provide the further info, I'll reopen the issue
