### ISSUE TITLE
How to parse a JSON array？

### ISSUE THREAD

**Issue by SickWorm** [jsonmodel/jsonmodel#580]
e.g.:
[{ "id": 10, "country": "Germany", "dialCode": 49, "isInEurope": true }, { "id": 11, "country": "English", "dialCode": 50, "isInEurope": true }]

it's there any `JSONModelArray` or `JSONModel<NSArray>` or some ways that I can parse this JSON array to an array object?

it's not a field of a JSON object, the whole JSON is an array, so I need to build a suiltable class for it.

**Comment by billinghamj** [comment]
Use one of these: https://github.com/jsonmodel/jsonmodel/blob/master/JSONModel/JSONModel/JSONModel.h#L182-L196
