### ISSUE TITLE
SWIFT JSON MODEL EXAMPLE ?

### ISSUE THREAD

**Issue by yogesh2209** [jsonmodel/jsonmodel#584]
Hi,

Please anyone can provide me with the swift example of JSON MODEL ?
//URGENT

**Comment by yogesh2209** [comment]
Instead of helping. You just closed this problem. 
Woah !! Very nice support. Thanks a lot !!

**Comment by yogesh2209** [comment]
If you have made this for SWIFT as well, then you should provide with the example.

**Comment by billinghamj** [comment]
https://github.com/jsonmodel/jsonmodel/blob/master/CONTRIBUTING.md#issues

**Comment by billinghamj** [comment]
See: https://github.com/jsonmodel/jsonmodel/blob/master/CONTRIBUTING.md#general-helpsupport

Github issues are not for providing support. You are being very rude, please read the contributing file shown to you before opening issues/PRs on any Github repo.
