### ISSUE TITLE
memory leaks

### ISSUE THREAD

**Issue by haoju-ios** [jsonmodel/jsonmodel#586]
### Issue Info

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform                |  ios
 Platform Version        | 10.3.1
JSONModel Version         | 1.7.0
 Integration Method      | manually
 
### Issue Description
```swift
import UIKit
import JSONModel

class ViewController: UIViewController {
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let dict: [String: Any] = [
            "test": [
                "desc": "哈哈",
                "id": 1
            ],
            "status": 9]
        
        if let response = try? Response(dictionary: dict) {
            print("\(response.toDictionary())")
        }
    }
}

class Response: JSONModel {
    var status: Int = 0
    var test: TestModel = TestModel()
    
}

@objc
class TestModel: JSONModel {
    var id: Int = 0
    var desc: String = ""
}
```
Create a "Single View Application" and add that code will cause memory leaks.
![image](https://cloud.githubusercontent.com/assets/21197252/25690823/cac2ec4a-30c7-11e7-930d-5562eecb5e84.png)
![image](https://cloud.githubusercontent.com/assets/21197252/25690834/dc7d5650-30c7-11e7-934f-7f7647ea7a04.png)

in the code "var test: TestModel = TestModel()", 
change it to "var test: TestModel?" or "var test: TestModel!" 
there will be no memory leaks。
Is there a problem with my using way?

**Comment by billinghamj** [comment]
Unfortunately I simply have no time to look into this, and I don't use Swift. If you are able to fix the issue, please open a PR providing the solution.
