### ISSUE TITLE
Optional Array json model property fails the whole parse operation.

### ISSUE THREAD

**Issue by gauravlnx** [jsonmodel/jsonmodel#587]
Hi,

I am using JsonModel library in my app. Today I noticed an issue in the library where the parse operation fails when an optional json model property fails to parse.

Here is an example: 
- Models:
```objective-c
@protocol ProductModel @end;

@interface ProductModel : JSONModel
@property (nonatomic) NSInteger productId;
@property (nonatomic) NSString *name;
@end

@interface OrderModel : JSONModel
@property (nonatomic) NSInteger orderId;
@property (nonatomic) NSArray <Optional, ProductModel> *products;
@end
```

Then constructing the `OrderModel` fails if following dictionary is used:
```objective-c
NSDictionary *dict = @{ @"orderId": @(1), @"products": @[@{@"productId": @(1)}, @{@"productId": @(2)}]};
 NSError *error;
    OrderModel *model = [[OrderModel alloc] initWithDictionary:dict error:&error];
    NSLog(@"Model: %@", model);
```

[JsonModelIssue.zip](https://github.com/jsonmodel/jsonmodel/files/992459/JsonModelIssue.zip)

**Comment by billinghamj** [comment]
This is failing because `name` is missing. Just mark it as `<Optional>`.

**Comment by gauravlnx** [comment]
Why reject the whole object if only an optional array property has the issue? why not set it as nil ?
In my project, the server sometimes sends incomplete data for the optional array of an JsonModel class. I think the common expectation in this case will be to discard that property as it is optional.

**Comment by billinghamj** [comment]
Then you should either fix your server, or make it an optional property. That is the correct behaviour of the library - it is not acceptable to just ignore errors.

**Comment by maksumon** [comment]
Create an NSNull+JSON category and import that in the JSONModel.m or in the {ProjectName}-Prefix.pch

```
#import <Foundation/Foundation.h>

@interface NSNull (JSON)

@end

#import "NSNull+JSON.h"

@implementation NSNull (JSON)

- (NSUInteger)length { return 0; }

- (NSInteger)integerValue { return 0; };

- (NSInteger)intValue { return 0; };

- (float)floatValue { return 0; };

- (NSString *)description { return @"0(NSNull)"; }

- (NSArray *)componentsSeparatedByString:(NSString *)separator { return @[]; }

- (id)objectForKey:(id)key { return nil; }

- (BOOL)boolValue { return NO; }

@end
```

I have been using that in many of my projects. I prefer to use this process so even if my server introduced any new JSON key for the API response, JSON parsing will still work without any crash or issue...
