### ISSUE TITLE
toDictionary can't support NSArray<model> 

### ISSUE THREAD

**Issue by raymondx0818** [jsonmodel/jsonmodel#592]
I found the function of toDictionary can't build a model with a model array property  like follow

@interface DTModelA: JSONModel
@property (strong) NSString *proA;
@property (strong) NSString *proA;
@end

interface DTModelB: JSONModel
@property (strong) NSArray< DTModelA *>* subModels;

DTModelB * b =[ [DTModelB alloc] init];
NSDictionary* dict =  [b toDictionary];

dict[subModels] not a NSArray<NSDictionary*> but a NSArray< DTModelA *>

**Comment by billinghamj** [comment]
Are you sure there is no asterisk in the angle brackets on the property declaration? For JSONModel, `NSArray <DTModelA *>` is not valid. See #591 also
