### ISSUE TITLE
Parsing of BOOL values results in crash

### ISSUE THREAD

**Issue by mstarke** [jsonmodel/jsonmodel#601]
Using JSONModel to parse BOOL flags into a model results in an exception in the KVC subsystem while trying to call ```setValue:forKey``` on the BOOL property here: https://github.com/jsonmodel/jsonmodel/blob/9ecd4f718d61bb13b7d301aeaa6c50d3462404a2/JSONModel/JSONModel/JSONModel.m#L341

The ```jsonValue``` is a ```NSTaggedPointerString``` which does not support ```charValue```

The following example will result in a crash:

```obj-c
@interface JMBTest : JSONModel
@property (assign) BOOL everythingIsOK;
@end

@implementation JMBTest
@end

int main(int argc, const char * argv[]) {
  NSString *jsonData = @"{ \"everythingIsOK\":\"true\" }";
  NSError *error;
  JMBTest *data = [[JMBTest alloc] initWithString:jsonData error:&error];
  return 0;
}
```

Platform is macOS 10.12.6. Xcode 9.0 10.13 SDK.

**Comment by billinghamj** [comment]
Anything to do with #585?

**Comment by mstarke** [comment]
Might be. I have to admit I have not took the time to deep-dive into the problem any further. This looks like it is the same cause but just the other end of the issue popping up while deserialising.

**Comment by mstarke** [comment]
I just ran the test with a version prior to the changes to primitive handling cd940e7ae0e74c927cd4293931f5d7e6465c343d and it works as expected without crashing.

**Comment by billinghamj** [comment]
Okay closing in favour of the existing issue then.
