### ISSUE TITLE
Got exception in toJSONDataWithKeys

### ISSUE THREAD

**Issue by nyeineiei** [jsonmodel/jsonmodel#604]
these are my custom models
```objc
@interface MainModel : JSONModel
    @property (nonatomic) NSArray<CCLSecurityChecklistModel *> *cclSecurityChecklist;
@end

@interface CCLSecurityChecklistModel : JSONModel
    @property (nonatomic) NSString *section;
    @property (nonatomic) NSString *location;
    @property (nonatomic) NSString *nfc;
    @property (nonatomic) NSArray <ContentModel *> *content;
@end

@interface ContentModel : JSONModel
    @property (nonatomic) NSString *question;
    @property (nonatomic) NSString *type;
    @property (nonatomic) NSString *required;
    @property (nonatomic) NSString *extra;
    @property (nonatomic) NSArray *choices;
    @property (strong, nonatomic) AnswerModel *answer;
@end
```

This is my implementation for converting Model to JsonString
```objc
- (void)rightBarButtonItemClicked{
    NSString *string = [self.cclSecurityChecklistModel toJSONString];
    NSError* error;
    NSString* json = [NSJSONSerialization JSONObjectWithData:string
                                                         options:NSJSONWritingPrettyPrinted
                                                           error:&error];
    NSLog(@"Json String %@",json);
}
```

Here I got the error in
```objc
-(NSData*)toJSONDataWithKeys:(NSArray*)propertyNames
```

![](https://lh3.googleusercontent.com/-735w1_b8wx4/Wf_qYmW6sII/AAAAAAAADAg/hREEy8M3tWsTpqz5YzeHTj7t-doU-WMggCL0BGAYYCw/h1287/Screen%2BShot%2B2017-11-06%2Bat%2B12.49.32%2BPM.png)

Could u please give any suggestions for this issue.

**Comment by billinghamj** [comment]
Sorry, you haven’t provided enough information:

The screenshot is the state of the application before the crash - I need to see what it looks like after the crash, so you need to continue one more like and then show it to me.

Second, your implementation for `AnswerModel` is missing.

At a glance though, it looks like the problem might be the arrays. You’ve used Obj-C generics, but JSONModel can’t see these because they’re present at compile time only. See: https://github.com/jsonmodel/jsonmodel/blob/master/README.md#model-collections

**Comment by billinghamj** [comment]
If you still need help and have provided the extra information, add a comment and I’ll reopen the issue.

**Comment by nyeineiei** [comment]
thanks for the replies. After crashing I got this exception.
> [JSONModel.m:1058] EXCEPTION: Invalid type in JSON write (CCLSecurityChecklistModel)

Here is the model for Answer
`@interface AnswerModel : JSONModel
  @property (nonatomic) NSMutableArray *value;
  @property (nonatomic) NSMutableArray *photos;
  @property (nonatomic) NSMutableArray *remarks;
  @end`
