### ISSUE TITLE
[HELP] How can i add tag?

### ISSUE THREAD

**Issue by invisible66** [jsonmodel/jsonmodel#606]
Hi, 
How can i add a spesific tag to json string?

That's my object 

        @interface NewMembershipHeader : JSONModel
        @property (strong, nonatomic) NSString *tokenid;
        @property (assign, nonatomic)  int usercode;
        @end

----

         NewMembershipHeader *header = [NewMembershipHeader new];
         header.tokenid = 5;
         header.usercode = 10;

String : `NSString *headerStr = [header toJSONString];`

Result : `{"tokenid":"5","usercode":10}`

I want : `{ "header": {"tokenid":"5","usercode":10}}`

How can i add `header` tag?

**Comment by billinghamj** [comment]
You need another outer model. e.g.:

```objc
@interface RootObject : JSONModel
@property (nonatomic) NewMembershipHeader *header;
@end
```
