### ISSUE TITLE
How could  NSArray contain muti protocols?

### ISSUE THREAD

**Issue by hsessay** [jsonmodel/jsonmodel#608]
our project have a base model is a JSONModel subclass , such as 

```objc
@protocol ModelOne, ModelTwo, ModelThree;

@interface PagedResult : JSONModel

@property (nonatomic, assign) NSInteger totalPage;
@property (nonatomic, assign) NSInteger currentPage;
@property (nonatomic, assign) NSInteger totalNum;
@property (nonatomic, assign) NSInteger numPerPage;
@property (nonatomic, copy) NSArray <ModelOne, ModelTwo, ModelThree> *resultList;

@end
```

can I do it like this? 
but I've tried it got some error,the return model is not the target model of mine.
or is there any best way to solve this case?

**Comment by billinghamj** [comment]
No, you can't do it like that.

You'd need to have a single superclass which override the relevant initialiser. e.g.: https://github.com/jsonmodel/jsonmodel/issues/229#issuecomment-52556421
