### ISSUE TITLE
CGRect CGPoint should be surpportted; OR NSValue should be surpported

### ISSUE THREAD

**Issue by heistings** [jsonmodel/jsonmodel#609]
I've met a crash with code below:

```
@interface TestJSONModel : JSONModel <AbstractJSONModelProtocol>

@property (nonatomic) NSInteger id;
@property (nonatomic, strong) NSString *country;
@property (nonatomic) BOOL isInEurope;

@property (nonatomic, strong) NSValue *rect;

@property (nonatomic) CGPoint point;

@end
```

```
- (void)testWithJSONModel
{
    TestJSONModel *model = [TestJSONModel new];
    
    model.id = 12345;
    model.country = @"China";
    model.isInEurope = NO;
    
//    model.rect = [NSValue valueWithCGRect:CGRectMake(5, 5, 5, 5)];
    
    model.point = CGPointMake(100, 100);
    
    NSDictionary *dict = [model toDictionary];
    
    TestJSONModel *targetModel = [(id <AbstractJSONModelProtocol>)[TestJSONModel alloc] initWithDictionary:dict error:NULL];
    
    XCTAssert(model.id == targetModel.id);
}
```

> JSONModel.m:1033: error: -[JSONModelTests testWithJSONModel] : failed: caught "Value transformer not found", "[JSONValueTransformer __JSONObjectFromCGPoint:] not found"

**Comment by heistings** [comment]
I'd like to convert a model object to dictionary first, and then save the dictionary to db with my db manager.

I think there must be a good reason using CGRect as a model property. All I need is to convert NSValue kind property to json dictionary.

**Comment by heistings** [comment]
When I try to convert a NSDictionary to JSONModel, I still met this issue.

```
@interface TestJSONModel : JSONModel <AbstractJSONModelProtocol>

@property (nonatomic) NSInteger id;
@property (nonatomic, strong) NSString *country;
@property (nonatomic) BOOL isInEurope;

@property (nonatomic, strong) NSValue *rect;

@property (nonatomic) CGPoint point;

@end
```

```
- (void)testDictionaryToJSONModel
{
    // > Error Domain=JSONModelErrorDomain Code=1 "Invalid JSON data: Type NSConcreteValue is not allowed in JSON." UserInfo={NSLocalizedDescription=Invalid JSON data: Type NSConcreteValue is not allowed in JSON., kJSONModelKeyPath=rect}
    NSDictionary *dict = @{
                           @"id": @(12345),
                           @"country": @"China",
                           @"dirty_key": @"dirty_value",
                           @"rect":[NSValue valueWithCGRect:CGRectMake(0, 0, 50, 50)],
                           @"isInEurope": @(NO),
                           @"point": [NSValue valueWithCGPoint:CGPointMake(10, 10)],
                           };
    
    NSError *error;
    TestJSONModel *targetModel = [[TestJSONModel alloc] initWithDictionary:dict error:&error];
    XCTAssert(targetModel);
    XCTAssert(targetModel.id == [[dict objectForKey:@"id"] integerValue]);
}
```

**Comment by heistings** [comment]
I think, it's reasonable for a user to save a CGRect via NSValue to DB. That is saving or loading a record as a NSDictionary.

[Database] <=> NSDictionary <=> JSONModel

**Comment by billinghamj** [comment]
This is something you'll need to do within your own code I'm afraid. JSONModel is only designed to work directly with native/direct JSON types.

If you'd like to use other types, you can [implement a transformer](https://github.com/jsonmodel/jsonmodel#custom-data-transformers), or override the [getters/setters](https://github.com/jsonmodel/jsonmodel#custom-getterssetters).

**Comment by heistings** [comment]
@billinghamj What do you think of ORM and JSONModel ? Are they individual parts of an App ?

Is it a good idea using NSDictionary as a middle layer between DB and Model ?

Please.

**Comment by heistings** [comment]
@billinghamj Thank you very much. I've tried with overriding the [getters/setters](https://github.com/jsonmodel/jsonmodel#custom-getterssetters) and it works well for me. It's great !

**Comment by billinghamj** [comment]
Great :)

Particularly given the fact that nobody is able to provide any proper support to its maintenance, JSONModel is intended to keep to a very specific and limited set of use-cases. Specifically, it helps take JSON strings and turn them into equivalent Obj-C models. Anything past that point is considered out-of-scope because it causes too much complexity.

So if you want to involve an ORM, that's obviously something you're welcome to do, but it won't be directly supported/assisted by the library.
