### ISSUE TITLE
*typedef*ing NSString makes JSONModel stop working.

### ISSUE THREAD

**Issue by foresightyj** [jsonmodel/jsonmodel#610]
I am working on restful api models generated by swagger. Because swagger codegen do not generate enums so I am working around them. I encountered a problem which I have hard time understanding (probably because I am not experienced with objective-c). 

I abstracted the problem into a minimal test case below, where **testExample** works but **testExampleAnother** fails. The error message is:

> caught "NSUnknownKeyException", "[<CountryModel2 0x78f96960> valueForUndefinedKey:]: this class is not key value coding-compliant for the key country."

`typedef`ing `GenderEnum` into `NSString`, which I think is definitely innocuous, is actually not the case.

![image](https://user-images.githubusercontent.com/1296736/35439533-18b98540-02d6-11e8-9c58-b8bf79ca314a.png)

```

#import <XCTest/XCTest.h>
#import "JSONModel.h"

@interface CountryModel : JSONModel
    @property (nonatomic) NSInteger id;
    @property (nonatomic) NSString *country;
    @property (nonatomic) NSString *dialCode;
    @property (nonatomic) BOOL isInEurope;
@end

@implementation CountryModel
@end

typedef NSString GenderEnum;

@interface CountryModel2 : JSONModel
@property (nonatomic) NSInteger id;
@property (nonatomic) GenderEnum *country;
@property (nonatomic) NSString *dialCode;
@property (nonatomic) BOOL isInEurope;
@end

@implementation CountryModel2
@end


@interface HelloEmptyTests : XCTestCase

@end

@implementation HelloEmptyTests

- (void)testExample {
    // This is an example of a functional test case.
    // Use XCTAssert and related functions to verify your tests produce the correct results.

    NSString *myJson = @"{ \"id\": 10, \"country\": \"Germany\", \"dialCode\": 49, \"isInEurope\": true }";

    NSError *error;
    CountryModel *country = [[CountryModel alloc] initWithString:myJson error:&error];

    XCTAssertEqualObjects(country.country, @"Germany");
}

- (void)testExampleAnother {
    // This is an example of a functional test case.
    // Use XCTAssert and related functions to verify your tests produce the correct results.

    NSString *myJson = @"{ \"id\": 10, \"country\": \"Germany\", \"dialCode\": 49, \"isInEurope\": true }";

    NSError *error;
    CountryModel2 *country = [[CountryModel2 alloc] initWithString:myJson error:&error];

    XCTAssertEqualObjects(country.country, @"Germany");
}

@end
```

**Comment by billinghamj** [comment]
I'm not sure that we can support this really, as I think it would effectively require reflection.

**Comment by foresightyj** [comment]
Thanks for the quick response. I will fall back to using `#define` instead. 

Is it related to objective-c's run time? I know roughly what it has there but didn't have time to study thoroughly.

**Comment by billinghamj** [comment]
I expect so, but also don't have time to look into it unfortunately.

Closing this for now. If you find a way around, please do PR :)
