### ISSUE TITLE
Different dictionary key of json dictionary with database dictionary

### ISSUE THREAD

**Issue by heistings** [jsonmodel/jsonmodel#612]
I'm trying to use NSDictionary as a middle layer between my jsonmodel and database.

Here is a simple example.

When I convert a json from server to jsonmodel, the json looks like:

```json
{
  "orderId": 104,
  "orderDetails": {
    "name": "Product #1",
    "price": {
      "usd": 12.95
    }
  }
}
```

But when I saving this jsonmodel to database, I'd like to convert the jsonmodel to a dictionary, which keys is exactly the same as column names with my table in database , like this:

```json
{
  "orderId": 104,
  "product_name": "Product #1",
  "price": 12.95
}
```

So, is there any possible to power the JSONKeyMapper method

```
- (instancetype)initWithModelToJSONDictionary:(NSDictionary <NSString *, NSString *> *)toJSON;
```

with ability:

```
- (instancetype)initWithModelToJSONDictionary:(NSDictionary <NSString *, NSArray *> *)toJSON;
```

?

It can be used like this:

```objective-c
+ (JSONKeyMapper *)keyMapper
{
    return [[JSONKeyMapper alloc] initWithModelToJSONDictionary:@{
                                                                  @"id": @"orderId",
                                                                  @"productName": @[@"productName", @"orderDetails.name"],
                                                                  @"price": @"orderDetails.price.usd"
                                                                  }];
}
```

**Comment by heistings** [comment]
Sure I can write two jsonmodel class, one for:

```json
{
  "orderId": 104,
  "orderDetails": {
    "name": "Product #1",
    "price": {
      "usd": 12.95
    }
  }
}
```

and another for:

```
{
  "orderId": 104,
  "product_name": "Product #1",
  "price": 12.95
}
```

But I don't think it's a good idea.

**Comment by heistings** [comment]
I notice there is a deprecated api of JSONKeyMapper, which seems to be relative with my issue:

```
- (instancetype)initWithJSONToModelBlock:(JSONModelKeyMapBlock)toModel modelToJSONBlock:(JSONModelKeyMapBlock)toJSON DEPRECATED_MSG_ATTRIBUTE("use initWithModelToJSONBlock:");
```

but the toModel param is ignored:

```
- (instancetype)initWithJSONToModelBlock:(JSONModelKeyMapBlock)toModel modelToJSONBlock:(JSONModelKeyMapBlock)toJSON
{
    return [self initWithModelToJSONBlock:toJSON];
}
```

And it seems not possible for JSONKeyMapper to supply two different conversion with only one mapping method:

```
- (NSString *)convertValue:(NSString *)value;
```

So it there any historical information about this issue ?

**Comment by heistings** [comment]
I've found #545, and I think #545 is relative to my issue.  Multiple KeyMappers is a good idea.

**Comment by billinghamj** [comment]
You can map from one key to another, including with nested keys, but you can't map to two different keys - you can't put an array as the value in the mapping dict.

If you're only ever going server -> local database, that should be fine. If you want to post the same object back up to the server again, you're probably going to need two models.

**Comment by billinghamj** [comment]
The deprecated method was deprecated because it was never actually used - I'm not sure why it was ever there in the first place tbh.

**Comment by billinghamj** [comment]
In relation to #545 - I think my PR #546 would probably cover this, but I don't have time to sort it out unfortunately. If everyone is happy for it to be merged and released, and it doesn't break any tests, I'd be happy to push it out.
