### ISSUE TITLE
JSONModel not working on iOS 11.3 when having nested JSONModels or array of JSONModels

### ISSUE THREAD

**Issue by Asbat** [jsonmodel/jsonmodel#617]
Hi there,

For some reason when we have a JSONModel with nested JSONModel properties or array of such, the JSONModel logic does not work.

For nested JSONModels it gives me the error:
MyTestNestedItem type not supported for MyTestWrapper.item

I tried to find out what's the problem and it seems that this method:
`-(BOOL)__isJSONModelSubClass:(Class)class`
returns NO even if "class" is really a subclass of JSONModel.

Does not work on devices with iOS 11.3. 
No issues with the 11.3 simulators or devices with previous versions.

Does anyone have the same issues?

**Comment by billinghamj** [comment]
I’m afraid I’m not currently able to help with this, but happy to review and merge any PRs if someone finds a solution.

**Comment by Asbat** [comment]
Really sorry about the noise. 

Since iOS 11.3 when using MessageUI framework in a project and you have a custom class named ATAsset which is a JSONModel then the black magic happens.
