### ISSUE TITLE
Framework or lib.a not found

### ISSUE THREAD

**Issue by msalmanST** [jsonmodel/jsonmodel#619]
Hi, 
I want to use this library but I dont wanna use the pod or carthage, I want to include it as a framework or library, but I do not found any framework or library. Can you please guide me for this. I don't wanna include the whole code of your library.

**Comment by billinghamj** [comment]
I'm afraid we don't provide support for that. You can compile it locally and figure it out from there if you want, but we aren't able to help with it.
