### ISSUE TITLE
-[JSONModel __importDictionary:withKeyMapper:validation:error:]

### ISSUE THREAD

**Issue by xhxuanchen** [jsonmodel/jsonmodel#620]
Please help me! I can't find why? Who can tell me possible reason. Thank you!

**Comment by billinghamj** [comment]
https://github.com/jsonmodel/jsonmodel/blob/master/CONTRIBUTING.md#general-helpsupport

**Comment by xhxuanchen** [comment]
This is a online bug. I find bug from Fabric.This bug crash sometimes.
[json.txt](https://github.com/jsonmodel/jsonmodel/files/2068018/json.txt)
[model.txt](https://github.com/jsonmodel/jsonmodel/files/2068022/model.txt)
