### ISSUE TITLE
An problem with better!!!

### ISSUE THREAD

**Issue by shang1219178163** [JSONModel/JSONModel#629]
I hope:
@"items" =>  items
@"list" =>  items
@"data" =>  items

+ (JSONKeyMapper *)keyMapper{
    return [[JSONKeyMapper alloc]initWithModelToJSONDictionary:@{@"items": @[@"items",@"list"@"data"],
                                                                 @"eTag": @"e_tag"
                                                                 }];
}

**Comment by billinghamj** [comment]
https://github.com/jsonmodel/jsonmodel/blob/master/CONTRIBUTING.md#general-helpsupport
