### ISSUE TITLE
JSON not generated correctly when you have an array of JSONModel objects

### ISSUE THREAD

**Issue by pahmed** [JSONModel/JSONModel#91]
If you have a JSONModel class which has an array or dictionary which contains JSONModel objects, the result json string is not generated correctly (it contains a lot of \n in the middle of the json string)

**Comment by xuqisheng** [comment]
`{
	"message": "",
	"code": "",
	"data": {
		"DdetailsDTOList": [],
		"DispatchesDTO": {
			"ddetailsList": [{
				"ddate": "2016-08-15 14:02:59",
				"deadline": "2016-08-15 22:11:18",
				"did": "pg201608150001",
				"dispatcher": "0002",
				"id": 260,
				"invalid": 1,
				"isout": 0,
				"repairmen": "ENG",
				"status": 1
			}, {
				"ddate": "2016-08-15 14:02:59",
				"deadline": "2016-08-17 21:36:47",
				"did": "pg201608150001",
				"dispatcher": "0002",
				"id": 271,
				"invalid": 0,
				"isout": 0,
				"repairmen": "ENG",
				"status": 1
			}],
			"dispatches": {
				"cstate": 0,
				"id": "pg201608150001",
				"rid": "bx201608080001",
				"sdate": "2016-08-17 13:28:25",
				"status": 2
			}
		},
		"Repairs": {
			"auditor": "0001",
			"depcode": "B",
			"empno": "FOHAZE",
			"equipment": 9999,
			"id": "bx201608080001",
			"isNew": 0,
			"level": 1,
			"location": 1,
			"pic": 0,
			"postdate": "2016-08-08 13:29:24",
			"reason": 9999,
			"register": "FOHAZE",
			"remark": "Hhh",
			"roomno": "329",
			"setrepairs": 0,
			"spe": 9999,
			"state": 0,
			"status": 3,
			"voice": 0
		}
	},
	"success": "true"
}`

**Comment by xuqisheng** [comment]
‘’‘json
{
	"message": "",
	"code": "",
	"data": {
		"DdetailsDTOList": [],
		"DispatchesDTO": {
			"ddetailsList": [{
				"ddate": "2016-08-15 14:02:59",
				"deadline": "2016-08-15 22:11:18",
				"did": "pg201608150001",
				"dispatcher": "0002",
				"id": 260,
				"invalid": 1,
				"isout": 0,
				"repairmen": "ENG",
				"status": 1
			}, {
				"ddate": "2016-08-15 14:02:59",
				"deadline": "2016-08-17 21:36:47",
				"did": "pg201608150001",
				"dispatcher": "0002",
				"id": 271,
				"invalid": 0,
				"isout": 0,
				"repairmen": "ENG",
				"status": 1
			}],
			"dispatches": {
				"cstate": 0,
				"id": "pg201608150001",
				"rid": "bx201608080001",
				"sdate": "2016-08-17 13:28:25",
				"status": 2
			}
		},
		"Repairs": {
			"auditor": "0001",
			"depcode": "B",
			"empno": "FOHAZE",
			"equipment": 9999,
			"id": "bx201608080001",
			"isNew": 0,
			"level": 1,
			"location": 1,
			"pic": 0,
			"postdate": "2016-08-08 13:29:24",
			"reason": 9999,
			"register": "FOHAZE",
			"remark": "Hhh",
			"roomno": "329",
			"setrepairs": 0,
			"spe": 9999,
			"state": 0,
			"status": 3,
			"voice": 0
		}
	},
	"success": "true"
}
'''

**Comment by xuqisheng** [comment]
like this.the result of *ddetailsList* is not a object ,but a dictionary

**Comment by xuqisheng** [comment]
![46081e7e-2d02-4e8f-928b-e5ce022cc5b6](https://cloud.githubusercontent.com/assets/4362447/17758603/5a5e58b0-6523-11e6-80d1-0fc08034240f.png)

**Comment by billinghamj** [comment]
@xuqisheng Open a new issue please. Don't continue using one from two years ago.
